### ISSUE TITLE
Wrong Link Speed on Neighbor Map 

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#589] opened 2019-05-22 11:48 UTC
## Expected Behavior
In Neighbor Map I expect that when Link Speed is enabled, the current speed of the connection is shown.

## Current Behavior
When link speed is enabled, the current speed of the connection is not shown correctly.
![Schermata a 2019-05-22 13-45-42](https://user-images.githubusercontent.com/31916347/58172147-060e8980-7c98-11e9-97f6-57e02475fcbb.png)

## Your Environment

App::Netdisco 	2.42.8
SNMP::Info 	3.68
DB Schema 	57
PostgreSQL 	9.6.13
Perl 	5.24.1

**Comment by ollyg** [comment] 2019-05-22 12:42
Hi @def-bs thanks for the report, but you've not indicated what the correct/incorrect values are?

Note that the 2G entries are Aggregated Link totals. So if you have a trunk/bundle/aggregate of 2x1G it will show 2G as the speed for the connection between the devices.

If this is not the cause, please can you indicate the precise error? Thanks,

**Comment by def-bs** [comment] 2019-05-22 12:46
I mean that are not shown correctly, it is shown as "2020GM"

![Schermata a 2019-05-22 14-45-36](https://user-images.githubusercontent.com/31916347/58175392-51c53100-7ca0-11e9-973c-150fa88dfc97.png)

**Comment by ollyg** [comment] 2019-05-22 12:49
@def-bs thanks! OK I will reply later with more questions, because I'd like to see what the connections are between the devices and what speeds are in the device_port_details table for those ports.

**Comment by ollyg** [comment] 2019-05-22 12:50
sorry I meant device_port_properties table, I think

**Comment by inphobia** [comment] 2019-05-22 14:13
also, if you hover your mouse over the incorrect link, you should see some info in the top right corner:
![image](https://user-images.githubusercontent.com/39005454/58181244-bcc83500-7cab-11e9-9cd2-59f856b8b578.png)

can you show that too?

having the 2 device models would also help. lenovo & some fortinet devices at least can report bogus speeds. our netmap currently uses i_speed_raw so even if the module has a fixup for i_speed, netmap can still show incorrect data.

https://github.com/netdisco/snmp-info/blob/e886190e8e110d3bc8ede533d8f225d384d97da7/lib/SNMP/Info/Layer3/Lenovo.pm#L104-L106


and a long shot, but if you use things like vpc or mlag discovery order of devices might play a role too.

**Comment by def-bs** [comment] 2019-05-22 14:16
![Schermata a 2019-05-22 16-15-42](https://user-images.githubusercontent.com/31916347/58181883-e5046380-7cac-11e9-85a3-5a33d3a17f8e.png)

**Comment by inphobia** [comment] 2019-05-22 14:19
and what kind of devices are these? vendor/model/os preferably

**Comment by def-bs** [comment] 2019-05-23 08:18
It is a "hp / 2510-24B", OS / Version | hp     Q.11.78 and HP J8697A Switch 5406zl, OS hp / K.16.02.0026

**Comment by inphobia** [comment] 2019-05-23 21:13
i don't really see any strangeness in that snmp::info module.

could you provide us with the output of:
```
netdisco-do psql -e "COPY (select ip,port,raw_speed from device_port_properties where ip = '10.1.100.252') TO STDOUT WITH CSV HEADER"
netdisco-do psql -e "COPY (select ip,port,type,speed,remote_ip,remote_port,remote_type,remote_id from device_port where ip = '10.1.100.252') TO STDOUT WITH CSV HEADER"
```

replace 10.1.100.252 with the ip of your device, and run it for both devices.

we would prefer the complete output but if it contains sensitive data you can always email it (or you can create a private github repo and give me and ollyg access, works surprisingly well)

**Comment by ollyg** [comment] 2019-05-27 13:43
What's happening here, I think, is that Netdisco is rendering two connections on top of each other with different speeds, which creates a jumble in the picture. You can see another example in @def-bs first screenshot showing 1G and 2G at the same time, top left of the pic.

I don't know why this happens - Netdisco should run an SQL query to aggregate all the links between each pair of devices, and show that as one link. It's doing it twice, with different total speed values (seems to be a G and an M value in the example of @def-bs).

Perhaps the "left" and "right" end of the links are swapped, or some data is missing from the DB. I'm trying to reproduce the error on my system...

(for ref, this will be the Virtual::DeviceLinks SQL query and line 168 onwards of Web::Plugin::Device::Neighbors)

**Comment by ollyg** [comment] 2019-05-27 14:38
right, I hope this is fixed in:
[master 88788534] #589 only show link with highest agg speed if map links between two devices are asymmetric

the cause is asymmetric device_port entries for the two devices. it can be reproduced by taking two devices with multiple links between and removing the remote_port entry on one port on one side, causing asymmetric results from the DeviceLinks query.

the patch sorts the DeviceLinks results so the highest aggregate speed is shown first and then subsequent links are skipped.

**Closed by ollyg** 2019-05-27 14:38 UTC
