### ISSUE TITLE
FR: multi tenancy

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#929] opened 2022-09-06 10:12 UTC
two parts to this:

1. the database connections and a way to switch schema. the multi db bit is already implemented (external databases but we can rename it) and the switch could be a UI component drop down in the title bar together with making the `schema()` call to Dancer use dynamic attr.
2. for the four searches (port, vlan, device, node) add a tickbox option to make global search across all tenancies. hmm this might mean that then the links from that to device details needs an extra query string param to specify tenancy

**Comment by inphobia** [comment] 2022-09-26 00:20
while only a hunch, i think this caused some regression in 2.057002

on a very slow device (cisco fabric interconnect 6332) netdisco-do discover now hangs at this step
```
SNMP::Info::_load_attr v_cvi_if : CISCO-VLAN-IFTABLE-RELATIONSHIP-MIB::cviRoutedVlanIfIndex : .1.3.6.1.4.1.9.9.128.1.1.1.1.3
SNMP::Info::_global load_uptime : SNMPv2-MIB::sysUpTime.0 : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global snmpEngineTime : SNMP-FRAMEWORK-MIB::snmpEngineTime.0 : .1.3.6.1.6.3.10.2.1.3.0
```
snmp timeout from the config is also completely ignored, this hangs for over 15 minutes before i killed it.

on the database side i'm suddenly seeing
```
postgres  7641  1948  0 01:53 ?        00:00:00 postgres: testdisc testdisc 10.1.10.249(58336) PARSE waiting
postgres  7642  1948  0 01:53 ?        00:00:00 postgres: testdisc testdisc 10.1.10.249(58338) idle in transaction
```
the amount of parse waiting continues to slowly rise.


with netdisco 2.055001 this does not happen:
```
SNMP::Info::_load_attr v_cvi_if : CISCO-VLAN-IFTABLE-RELATIONSHIP-MIB::cviRoutedVlanIfIndex : .1.3.6.1.4.1.9.9.128.1.1.1.1.3
SNMP::Info::_global load_uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global snmpEngineTime : SNMP-FRAMEWORK-MIB::snmpEngineTime.0 : .1.3.6.1.6.3.10.2.1.3.0
[1664] 2022-09-25 23:50:01 debug  [10.40.254.42] db/ports - removed 0 port entries from DevicePortPower
[1664] 2022-09-25 23:50:01 debug  [10.40.254.42] db/ports - removed 167 port entries from DevicePortProperties
[1664] 2022-09-25 23:50:01 debug  [10.40.254.42] db/ports - removed 0 port entries from DevicePortSsid
```

both netdisco versions are running on the same server (different user) and are using postgres13 on a different server via tcp.

**Comment by inphobia** [comment] 2022-09-26 01:22
also happens when running discover via webinterface and on fast devices.

it seems these 2 could be the cause:
 testdisc | DELETE FROM device_port_power WHERE ( ip IN ( SELECT me.ip FROM device_port me WHERE ( me.ip = $1 ) ) )
 testdisc | LOCK TABLE "device_port" IN ACCESS EXCLUSIVE MODE

**Comment by inphobia** [comment] 2022-09-26 02:04
found a handy query to find locker & locked statements (via https://medium.com/compass-true-north/postgresql-lessons-we-learned-the-hard-way-663ddf666e4 )
```
select
  blocked_psa.pid as blocked_pid,
  blocked_psa.usename as blocked_usename,
  blocked_psa.application_name as blocked_application_name,
  blocked_psa.state as blocked_state,
  blocked_psa.query as blocked_query,
  '~~~~~~~~~~' as divider,
  blocking_psa.pid as blocking_pid,
  blocking_psa.usename as blocking_usename,
  blocking_psa.application_name as blocking_application_name,
  blocking_psa.state as blocking_state,
  blocking_psa.query as blocking_query
from pg_catalog.pg_stat_activity blocked_psa
join pg_catalog.pg_stat_activity blocking_psa on blocking_psa.pid = any(pg_catalog.pg_blocking_pids(blocked_psa.pid));
```

which points to the same queries:
```
 blocked_pid | blocked_usename | blocked_application_name | blocked_state |                                              blocked_query                                              |  divider   | blocking_pid | blocking_usename | blocking_application_name |   blocking_state    |                  blocking_query
-------------+-----------------+--------------------------+---------------+---------------------------------------------------------------------------------------------------------+------------+--------------+------------------+---------------------------+---------------------+---------------------------------------------------
        8491 | testdisc        |                          | active        | DELETE FROM device_port_power WHERE ( ip IN ( SELECT me.ip FROM device_port me WHERE ( me.ip = $1 ) ) ) | ~~~~~~~~~~ |         8492 | testdisc         |                           | idle in transaction | LOCK TABLE "device_port" IN ACCESS EXCLUSIVE MODE
```

**Comment by ollyg** [comment] 2022-09-27 12:06
@inphobia you are right, I think I can at least reproduce this ... looking now

**Comment by ollyg** [comment] 2022-09-27 15:31
@inphobia should be fixed in latest release! sorry about that

**Comment by inphobia** [comment] 2022-09-27 21:31
that seems to have done the trick, great job as always!

**Comment by inphobia** [comment] 2022-09-27 21:33
shouldn't have closed this, my issue is fixed but i don't know if you're done with the actual subject of this issue, the multi tenancy.

**Closed** 2023-04-22 16:41 UTC
Labels: assigned-to-project
