### ISSUE TITLE
broadcast addresses are discovered as devices when scanning large prefix

### ISSUE THREAD

**Issue by RickdeJager** [netdisco/netdisco#639] opened 2019-08-27 15:25 UTC
When a device, for example a core switch, has multiple IP addresses each of will be represented by a node. While this may be useful in some cases, it would be nice to be able to combine all nodes with the same serial number into one.

## Expected Behavior

To keep the graph useful, it would be nice to be able to combine multiple nodes representing the same switch into one node.

## Current Behavior

When viewing all devices in a graph, a core switch with multple IPs will get multiple entries.

## Possible Solution

A toggle to combine all nodes with the same serial number (or some other identifier) into one node.

## Steps to Reproduce (for bugs)

1. Setup a core switch with multiple vlans.
2. Connect other switches to it, on different vlans
3. scan all vlans.

## Context

Here's a screenshot of our current environment. Each of those center nodes represents the same core switch.  

![image](https://user-images.githubusercontent.com/29239050/63784739-63e1eb80-c8ef-11e9-887d-e5484dac527f.png)  
If there was an option to combine these, the graph would be much more useful.

**Comment by inphobia** [comment] 2019-08-27 15:31
that shouldn't happen, please provide the following info:;

* what netdisco version are you running?
* snmp::info vcersion
* devices where this happens (vendor/model/os)
* any vrfs in use?


side note, could be related to https://github.com/netdisco/netdisco/issues/524

**Comment by rc9000** [comment] 2019-08-27 15:55
You can use [device_identity](https://github.com/netdisco/netdisco/wiki/Configuration#device_identity) to give Netdisco hints about the management IP you'd like to add to the database. 

I think you'll need to delete and re-discover the switches after you've set this up.

**Comment by inphobia** [comment] 2019-08-27 21:52
the live netmap, one of our coolest features and one of the most complex imo.

i actually like the concept of ordering by serials, but it shouldn't be required. how did you add those devices to netdisco, one by one or as a whole subnet?

**Comment by RickdeJager** [comment] 2019-08-28 07:26
Sorry for not including the version information, I figured the feature didn't exist yet.  
  

We're using the lastest Docker build:
* App::Netdisco: 2.42.10  
* SNMP::Info: 3.68

The devices in the screenshot are Cisco IOS and HP Procurve switches, vrf is not configured.  I'll see if I can get it to work with device_identity, thanks for the heads-up

**Comment by inphobia** [comment] 2019-08-28 20:33
side note, are you using any non default options anywhere?

**Comment by RickdeJager** [comment] 2019-08-29 08:48
@inphobia I only changed the ldap settings, didn't touch anything else.

@rc9000 the device_identity fix worked like a charm, leaving it here in case someone stumbles upon this issue, Thanks!  
```yaml
[...]
 device_identity:
   'any':
      - !!perl/regexp ^COMPANY-3570X-48-01.*$
[...]
```

**Comment by RickdeJager** [comment] 2019-08-29 09:39
The underlying issue appears to be that for some broadcast addresses, the core switch was the only one replying. Each of these broadcast addresses got it's own node. Netdisco did correctly combine all gateways into the same node.  
  
Blocking the broadcast addresses with no_discover also solves the issue.  
  
I'm not 100% sure if this is a common issue, or if we setup our network in a unusual way, but thank you both for your help!

**Comment by rc9000** [comment] 2019-08-29 09:51
Yes the broadcast explanation makes sense. The whole "node combining" setup is based on the device_ip table in the DB, which has the "canonical" address (the first one discovery was run against), and then all other addresses on the device in the alias section. But broadcast addresses aren't in there, so discovering one of them would look like a new device.

Do you remember if you manually passed any broadcast addresses to the discovery? Because otherwise I don't quite understand how it would happen, but that might be a lack of knowledge on my part.

**Comment by RickdeJager** [comment] 2019-08-29 15:25
I think it happened because I tried to scan multiple /24 subnets in one go by using several larger subnets.   
  

For example, instead of scanning 10.0.0.0/24 till 10.0.15.0/24 manually, I ran discovery on 10.0.0.0/20.  
While this seemed like a good idea at the time, it also means that 10.0.0.255 is not seen as a broadcast address because the subnet mask is different.

**Comment by rc9000** [comment] 2019-08-29 17:34
Ah ok, I think mystery solved. Out of curiosity, did you ping-sweep your network/enumerate the addresses and then run discover in a loop over it? Because the builtin subnet discovery doesn't even let you hand it more than a /23:


    netdisco@lanmgmt03:~ $ netdisco-do discover -d 10.0.0.0/20
    [22616] 2019-08-29 17:24:00  info App::Netdisco version 2.042010 loaded.
    [22616] 2019-08-29 17:24:00  info discover: aborted - unwise to attempt 4094 jobs at once


Looks like @ollyg already anticipated this issue 👍 

Anyhow so for the record and future readers, to discover all of your network, the best choices are probably:

   * just discover a couple of core IPs in the GUI and let the neighbor discovery to the rest
   * or with this subnet approach,  just pass the subnets actually used in your organsiation
   * or as  @RickdeJager did, use discover_no or device_identity to not discover broadcast addresses

Now I'm actually wondering what happens if multiple devices with snmp agents respond on the same broadcast... I imagine this would lead to some interesting database content :)

**Comment by ollyg** [comment] 2019-08-29 18:32
Also to note that ideally netdisco would have deduplicated the devices
based on common serial number.

But I believe at present this is only done for removing queued jobs (a good
start but subject to races of course).

The removal of duplicate devices automatically (pr suppression of adding
devices) wasn’t implemented (as a measure of caution) and instead there’s a
duplicate device report, I think.

Oliver.

**Comment by RickdeJager** [comment] 2019-08-30 08:56
@rc9000 Are you sure? The web interface seems to happily accept 10.0.0.0/20. The Job queue also fills up with all contained addresses.

**Comment by rc9000** [comment] 2019-08-30 10:05
@RickdeJager I had no idea the GUI can do that :) It's kinda inconsistent with the CLI then, but that's a low-prio PR for another time.

**Comment by inphobia** [comment] 2019-08-30 14:36
perhaps the check on the cli:
https://github.com/netdisco/netdisco/blob/a734890055ce417273d7fc9c2a0434a95589cc49/bin/netdisco-do#L117-L121

should be done only if we don't queue the jobs:
https://github.com/netdisco/netdisco/blob/a734890055ce417273d7fc9c2a0434a95589cc49/bin/netdisco-do#L142

if you have a macwalk with 1000 devices netdisco will also queue 1000 jobs happily.

**Comment by inphobia** [comment] 2019-08-30 14:41
also need to check what happens with non discovered devices, will they end up in snmp connnect failures or will they just be forgotten.

**Comment by ollyg** [comment] 2019-09-03 08:38
> @RickdeJager I had no idea the GUI can do that :) It's kinda inconsistent with the CLI then, but that's a low-prio PR for another time.

the inconsistency is because submitted thru the web interface the operation is asynchronous... the jobs are submitted to the queue. at the CLI the user would have to wait for the jobs to be done. that was the original rationale, but that was before CLI supported the --enqueue param.

**Comment by ollyg** [comment] 2019-09-03 08:40
closing this ticket as we now know the cause for the issue... discover scanning a large prefix caused the enclosed broadcast addresses to be picked up as new devices. Netdisco is not to know that they are broadcast addresses.

**Closed by ollyg** 2019-09-03 08:40 UTC
