### ISSUE TITLE
IP inventory CSV is not complet

### ISSUE THREAD

**Issue by earendilfr** [netdisco/netdisco#717] opened 2020-04-29 04:22 UTC
# Expected and Current Behavior
I have an issue with the export of IP inventory to CSV.
When I try to export a report with 66 records, my CSV has only 12 row (and not the expected 66 rows from the inventory

No error message in log file (from backend or web daemon) are show during the export.
After restart of both service, still the same issue
It seems like the incident #715 but not sure...

## Steps to Reproduce (for bugs)
1. Go to Report > IP > IP Inventory 
2. Select a network on your site (in my case, the IP range 10.23.253.0/24)
3. See the 66 rows on Web interface
4. Click on export to CSV button
5. Receive a file with only 12 rows (header included)

## Your Environment
* Netdisco version used: 2.45.2
* SNMP::Info version used: 3.70
* DB Schema: 62

**Comment by zoeloe** [comment] 2020-05-01 20:02
I was suspecting in issue #715 a big,... but now I checked again and the number off record exported is correct, BUT,... the CSV file still contains HTML and Javascript portions.

**Comment by ollyg** [comment] 2020-05-15 10:48
Unfortunately I cannot reproduce this

**Comment by ollyg** [comment] 2020-05-15 10:50
Hi @earendilfr the other ticket suggests that a restart of the backend and frontend might fix it. Please can you do that and confirm?

**Comment by zoeloe** [comment] 2020-05-15 10:59
The HTML and Javascript leak seem to be related to #715. Another backend and frontend restart and the CSV export was OK. I'll wait till 2.045003 to check again.

**Comment by zoeloe** [comment] 2020-05-15 19:40
CSV file format seems to be correct in 2.045003, but that was after the web and backend restart as standard upgrade procedure off course. I'll check later again.

**Comment by ollyg** [comment] 2020-05-17 11:46
probably fixed by https://github.com/netdisco/netdisco/commit/0d3aec8c17e2cc424d3c79514e5d05188f30dcde

**Closed by ollyg** 2020-05-17 11:46 UTC
Labels: stalled
