### ISSUE TITLE
Map with VLAN filter omits unconnected devices

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#498] opened 2019-02-04 10:34 UTC
## Expected Behavior
I have already opened an issue some days ago, I have noted a bug in netdisco the VLAN are not correctly updated, even when a device is deleted, a wrong VLAN is shown.

See: https://github.com/netdisco/netdisco/issues/497#issuecomment-459756747

P.S. I belive the update system is not working very well. Even the software version sometimes does not work, showing the wrong netdisco version. 

# Current Behavior
Old info are kept and are not updated. For example VLANs. Only way to update is running netdisco-do 

## Possible Solution
Force an update every x minutes? 

## Steps to Reproduce (for bugs)
Some VLAN is changed. Then, I search for a specific VLAN, the map is shown with the old data.
Even if you delete the device and readd it, the VLAN are shown right, but the map is still wrong.
I tried to delete the cache but the issue persists

## Your Environment
Software	Version
App::Netdisco	2.40.3
SNMP::Info	3.64
DB Schema	53
PostgreSQL	9.6.10
Perl	5.24.1

Thank you

**Comment by inphobia** [comment] 2019-02-04 11:07
i don't see how this is possible, since each discover deletes and recreate the device entry.

did you run a discoverall via the webinterface after the upgrade? that should have corrected all old data in the database.




about the ps:
if it sometimes shows the wrong version something seems to be very wrong with your installation.

perhaps there are multiple versions running (either on the same or different servers) or the database somehow got corrupted, it should never report another version at the one that's running.

another option that your operating system has a netdisco and/or snmp::info package installed via the package manager. while that should not cause any issues if you used the install method from our docs, it's generally not recommended.

**Comment by def-bs** [comment] 2019-02-07 08:57
Hi,

the version problem is a thing that is going on for a lot of time, I do not have multiple version running.
I remember a issue about that on github that was solved by Oliver.
Now it is working. 


The VLAN issue is still ongoing altough. The VLANs are correctly reported if I search them manually but on the map are not shown.


I am trying the "Discover All", but it will take some times to complete, because I have a lot of devices.

**Comment by ollyg** [comment] 2019-02-20 07:33
Hi, please can we have some screenshots, especially of:

> Even if you delete the device and readd it, the VLAN are shown right, but the map is still wrong.

**Comment by ollyg** [comment] 2019-02-20 07:44
Hi, please can you clarify in what way is the map wrong?
I can see three devices (.10) which all seem to carry the VLAN. There is one missing device - is this the problem you refer to?

**Comment by ollyg** [comment] 2019-02-20 07:44
(p.s. many thanks for the screenshots and quick reply!)

**Comment by def-bs** [comment] 2019-02-20 07:46
I searched for the devices on VLAN 472. As you can see I get 4 devices but if I do the same search in the map i get only 3.

So the map is not showing the right number of devices.

**Comment by ollyg** [comment] 2019-02-20 07:49
OK - thanks! I'll look into this.

**Comment by inphobia** [comment] 2019-02-28 18:56
question, is the device you are missing connected to any other device known by netdisco?

can you run:
```
netdisco-do psql -e "select ip,port,up,remote_ip,remote_port,vlan from device_port where ip = '172.16.251.10'"
netdisco-do psql -e "select ip,port,up,remote_ip,remote_port,vlan from device_port where ip = '172.16.251.15'"
```

thx

**Comment by def-bs** [comment] 2019-03-01 09:28
./netdisco-do psql -e "select ip,port,up,remote_ip,remote_port,vlan from device_port where ip = '172.16.251.10'"
[12728] 2019-03-01 09:26:26  info App::Netdisco version 2.040003 loaded.
[12728] 2019-03-01 09:26:26  info psql:  started at Fri Mar  1 10:26:26 2019
---------------+---------------------------+------+----------------+-------------+------
 172.16.251.10 | D23                       | down |                |             | 67
 172.16.251.10 | E3                        | up   |                |             | 310
 172.16.251.10 | VLAN110                   | up   |                |             |
 172.16.251.10 | VLAN24                    | up   |                |             |
 172.16.251.10 | B2                        | up   |                |             | 1
 172.16.251.10 | D15                       | up   |                |             | 67
 172.16.251.10 | VLAN450                   | up   |                |             |
 172.16.251.10 | VLAN452                   | up   |                |             |
 172.16.251.10 | F1                        | up   |                |             | 67
 172.16.251.10 | C24                       | down |                |             | 67
 172.16.251.10 | VLAN211                   | up   |                |             |
 172.16.251.10 | C17                       | up   |                |             | 67
 172.16.251.10 | C5                        | up   |                |             | 67
 172.16.251.10 | D9                        | up   |                |             | 67
 172.16.251.10 | C16                       | up   |                |             | 67
 172.16.251.10 | B24                       | down |                |             | 67
 172.16.251.10 | B14                       | down |                |             | 67
 172.16.251.10 | VLAN100                   | up   |                |             |
 172.16.251.10 | C1                        | up   |                |             | 67
 172.16.251.10 | D18                       | up   |                |             | 67
 172.16.251.10 | F5                        | down |                |             | 67
 172.16.251.10 | D1                        | up   |                |             | 67
 172.16.251.10 | VLAN454                   | up   |                |             |
 172.16.251.10 | B3                        | up   |                |             | 24
 172.16.251.10 | D12                       | up   |                |             | 67
 172.16.251.10 | E13                       | down |                |             | 67
 172.16.251.10 | E14                       | down |                |             | 67
 172.16.251.10 | C8                        | up   |                |             | 67
 172.16.251.10 | E15                       | down |                |             | 67
 172.16.251.10 | VLAN357                   | up   |                |             |
 172.16.251.10 | E17                       | down |                |             | 67
 172.16.251.10 | VLAN310                   | up   |                |             |
 172.16.251.10 | VLAN422                   | up   |                |             |
 172.16.251.10 | A1                        | down |                |             | 25
 172.16.251.10 | F6                        | down |                |             | 67
 172.16.251.10 | E7                        | down |                |             | 310
 172.16.251.10 | D16                       | down |                |             | 67
 172.16.251.10 | D14                       | down |                |             | 67
 172.16.251.10 | C14                       | down |                |             | 67
 172.16.251.10 | E23                       | down |                |             | 67
 172.16.251.10 | VLAN999                   | up   |                |             |
 172.16.251.10 | E19                       | up   |                |             | 67
 172.16.251.10 | D2                        | down |                |             | 67
 172.16.251.10 | B10                       | down |                |             | 67
 172.16.251.10 | F23                       | down |                |             | 67
 172.16.251.10 | D21                       | down |                |             | 67
 172.16.251.10 | A2                        | down |                |             | 1
 172.16.251.10 | E16                       | down |                |             | 67
 172.16.251.10 | C6                        | up   |                |             | 67
 172.16.251.10 | C9                        | up   |                |             | 67
 172.16.251.10 | VLAN432                   | up   |                |             |
 172.16.251.10 | C23                       | down |                |             | 67
 172.16.251.10 | B12                       | down |                |             | 67
 172.16.251.10 | F3                        | up   |                |             | 67
 172.16.251.10 | F4                        | up   |                |             | 67
 172.16.251.10 | C15                       | down |                |             | 67
 172.16.251.10 | C11                       | down |                |             | 67
 172.16.251.10 | E12                       | up   |                |             | 310
 172.16.251.10 | D24                       | down |                |             | 67
 172.16.251.10 | B4                        | up   |                |             | 67
 172.16.251.10 | B21                       | down |                |             | 67
 172.16.251.10 | F13                       | up   |                |             | 67
 172.16.251.10 | B19                       | up   |                |             | 67
 172.16.251.10 | VLAN212                   | up   |                |             |
 172.16.251.10 | E9                        | down |                |             | 310
 172.16.251.10 | F24                       | down |                |             | 1
 172.16.251.10 | C2                        | up   |                |             | 67
 172.16.251.10 | C22                       | down |                |             | 67
 172.16.251.10 | F16                       | up   |                |             | 67
 172.16.251.10 | B20                       | up   |                |             | 67
 172.16.251.10 | B13                       | down |                |             | 1
 172.16.251.10 | D4                        | up   |                |             | 67
 172.16.251.10 | C18                       | up   |                |             | 67
 172.16.251.10 | C10                       | up   |                |             | 67
 172.16.251.10 | VLAN472                   | up   |                |             |
 172.16.251.10 | F8                        | up   |                |             | 67
 172.16.251.10 | F15                       | up   |                |             | 67
 172.16.251.10 | VLAN5                     | down |                |             |
 172.16.251.10 | F9                        | up   |                |             | 67
 172.16.251.10 | VLAN462                   | up   |                |             |
 172.16.251.10 | E11                       | up   |                |             | 310
 172.16.251.10 | B1                        | up   |                |             | 1
 172.16.251.10 | F21                       | down |                |             | 67
 172.16.251.10 | B17                       | up   |                |             | 67
 172.16.251.10 | VLAN6                     | down |                |             |
 172.16.251.10 | E1                        | down |                |             | 310
 172.16.251.10 | E2                        | up   |                |             | 310
 172.16.251.10 | E18                       | up   |                |             | 67
 172.16.251.10 | F19                       | up   |                |             | 67
 172.16.251.10 | B18                       | up   |                |             | 67
 172.16.251.10 | F18                       | down |                |             | 67
 172.16.251.10 | B23                       | down |                |             | 67
 172.16.251.10 | C21                       | up   |                |             | 67
 172.16.251.10 | E22                       | down |                |             | 67
 172.16.251.10 | B11                       | down |                |             | 67
 172.16.251.10 | VLAN120                   | up   |                |             |
 172.16.251.10 | A16                       | up   | 172.16.251.17  | 24          | 1
 172.16.251.10 | A4                        | up   | 172.16.251.98  | 52          | 1
 172.16.251.10 | D7                        | down |                |             | 67
 172.16.251.10 | F22                       | down |                |             | 67
 172.16.251.10 | F11                       | up   |                |             | 67
 172.16.251.10 | D20                       | up   |                |             | 67
 172.16.251.10 | VLAN412                   | up   |                |             |
 172.16.251.10 | E21                       | down |                |             | 67
 172.16.251.10 | B22                       | down |                |             | 67
 172.16.251.10 | C13                       | up   |                |             | 67
 172.16.251.10 | VLAN140                   | up   |                |             |
 172.16.251.10 | E20                       | down |                |             | 67
 172.16.251.10 | E24                       | down |                |             | 67
 172.16.251.10 | B6                        | down |                |             | 67
 172.16.251.10 | Switch loopback interface | down |                |             |
 172.16.251.10 | D11                       | up   |                |             | 67
 172.16.251.10 | VLAN418                   | up   |                |             |
 172.16.251.10 | E5                        | down |                |             | 310
 172.16.251.10 | B8                        | down |                |             | 67
 172.16.251.10 | E10                       | down |                |             | 310
 172.16.251.10 | C4                        | up   |                |             | 67
 172.16.251.10 | E4                        | up   |                |             | 310
 172.16.251.10 | F17                       | up   |                |             | 67
 172.16.251.10 | F10                       | up   |                |             | 67
 172.16.251.10 | B16                       | up   |                |             | 67
 172.16.251.10 | E6                        | down |                |             | 310
 172.16.251.10 | VLAN474                   | up   |                |             |
 172.16.251.10 | B9                        | down |                |             | 67
 172.16.251.10 | C12                       | up   |                |             | 67
 172.16.251.10 | VLAN25                    | down |                |             |
 172.16.251.10 | D17                       | down |                |             | 67
 172.16.251.10 | F2                        | down |                |             | 67
 172.16.251.10 | D6                        | up   |                |             | 67
 172.16.251.10 | D10                       | up   |                |             | 67
 172.16.251.10 | C3                        | down |                |             | 67
 172.16.251.10 | D13                       | up   |                |             | 67
 172.16.251.10 | E8                        | down |                |             | 310
 172.16.251.10 | A18                       | up   | 172.16.251.111 | 9           | 1
 172.16.251.10 | A23                       | up   | 10.101.53.182  | A23         |
 172.16.251.10 | A3                        | up   | 172.16.251.20  | 45          | 1
 172.16.251.10 | A6                        | up   | 172.16.251.70  | 26          | 1
 172.16.251.10 | D22                       | down |                |             | 67
 172.16.251.10 | VLAN414                   | up   |                |             |
 172.16.251.10 | F7                        | up   |                |             | 67
 172.16.251.10 | VLAN15                    | up   |                |             |
 172.16.251.10 | F14                       | up   |                |             | 67
 172.16.251.10 | B7                        | down |                |             | 67
 172.16.251.10 | DEFAULT_VLAN              | up   |                |             |
 172.16.251.10 | VLAN424                   | up   |                |             |
 172.16.251.10 | C7                        | up   |                |             | 67
 172.16.251.10 | VLAN67                    | up   |                |             |
 172.16.251.10 | D5                        | up   |                |             | 67
 172.16.251.10 | D8                        | up   |                |             | 67
 172.16.251.10 | B15                       | up   |                |             | 67
 172.16.251.10 | C19                       | down |                |             | 67
 172.16.251.10 | VLAN210                   | up   |                |             |
 172.16.251.10 | B5                        | down |                |             | 67
 172.16.251.10 | D19                       | down |                |             | 67
 172.16.251.10 | C20                       | down |                |             | 67
 172.16.251.10 | D3                        | up   |                |             | 67
 172.16.251.10 | VLAN464                   | up   |                |             |
 172.16.251.10 | F12                       | down |                |             | 67
 172.16.251.10 | A10                       | up   | 172.16.251.103 | 48          | 1
 172.16.251.10 | A11                       | up   | 10.128.250.19  | F24         | 1
 172.16.251.10 | A12                       | up   | 172.16.251.60  | 51          | 1
 172.16.251.10 | A13                       | up   | 172.16.251.122 | 10          | 1
 172.16.251.10 | A14                       | up   | 172.16.251.106 | 49          | 1
 172.16.251.10 | F20                       | up   | 172.16.251.12  | 48          | 1
 172.16.251.10 | A15                       | up   | 172.16.251.18  | 28          | 1
 172.16.251.10 | A17                       | up   | 172.16.251.99  | 10          | 1
 172.16.251.10 | A19                       | up   | 172.16.251.84  | 24          | 1
 172.16.251.10 | A20                       | up   | 172.16.251.22  | 27          | 1
 172.16.251.10 | A21                       | up   | 172.16.251.61  | 10          | 1
 172.16.251.10 | A22                       | up   | 172.16.251.85  | 10          | 1
 172.16.251.10 | Trk1                      | up   | 172.16.251.15  | Trk1        | 1
 172.16.251.10 | A24                       | up   | 10.101.53.182  | A24         |
 172.16.251.10 | A5                        | up   | 172.16.251.100 | 47          | 1
 172.16.251.10 | A7                        | up   | 172.16.251.80  | 48          | 1
 172.16.251.10 | A8                        | up   | 172.16.251.109 | 45          | 1
 172.16.251.10 | A9                        | up   | 172.16.251.120 | 45          | 1
(176 righe)

(END)

**Comment by def-bs** [comment] 2019-03-01 09:29
./netdisco-do psql -e "select ip,port,up,remote_ip,remote_port,vlan from device_port where ip = '172.16.251.15'"
[12755] 2019-03-01 09:28:56  info App::Netdisco version 2.040003 loaded.
[12755] 2019-03-01 09:28:56  info psql:  started at Fri Mar  1 10:28:56 2019
      ip       |           port            |  up  |   remote_ip    | remote_port | vlan
---------------+---------------------------+------+----------------+-------------+------
 172.16.251.15 | A20                       | down |                |             | 1
 172.16.251.15 | VLAN464                   | up   |                |             |
 172.16.251.15 | VLAN474                   | up   |                |             |
 172.16.251.15 | A1                        | up   | 172.16.251.140 | 45          | 1
 172.16.251.15 | A23                       | up   | 10.96.0.1      | A23         |
 172.16.251.15 | A4                        | up   | 172.16.251.160 | 45          | 1
 172.16.251.15 | VLAN422                   | up   |                |             |
 172.16.251.15 | A7                        | down |                |             | 1
 172.16.251.15 | VLAN408                   | up   |                |             |
 172.16.251.15 | A9                        | down |                |             | 1
 172.16.251.15 | VLAN462                   | up   |                |             |
 172.16.251.15 | A12                       | down |                |             | 1
 172.16.251.15 | VLAN67                    | up   |                |             |
 172.16.251.15 | VLAN310                   | up   |                |             |
 172.16.251.15 | VLAN472                   | up   |                |             |
 172.16.251.15 | VLAN110                   | up   |                |             |
 172.16.251.15 | A8                        | down |                |             | 1
 172.16.251.15 | VLAN414                   | up   |                |             |
 172.16.251.15 | VLAN454                   | up   |                |             |
 172.16.251.15 | VLAN424                   | up   |                |             |
 172.16.251.15 | DEFAULT_VLAN              | up   |                |             |
 172.16.251.15 | A10                       | up   | 10.114.22.247  | 45          | 1
 172.16.251.15 | VLAN418                   | up   |                |             |
 172.16.251.15 | Switch loopback interface | up   |                |             |
 172.16.251.15 | A11                       | down |                |             | 1
 172.16.251.15 | A21                       | down |                |             | 1
 172.16.251.15 | VLAN432                   | up   |                |             |
 172.16.251.15 | A22                       | down |                |             | 67
 172.16.251.15 | A15                       | up   | 172.16.251.151 | 10          | 1
 172.16.251.15 | A17                       | up   | 172.16.251.172 | 10          | 1
 172.16.251.15 | A18                       | up   | 172.16.251.181 | 10          | 1
 172.16.251.15 | A2                        | up   | 172.16.251.240 | 25          | 1
 172.16.251.15 | A24                       | up   | 10.96.0.1      | A24         |
 172.16.251.15 | A3                        | up   | 172.16.251.150 | 45          | 1
 172.16.251.15 | A19                       | down |                |             | 1
 172.16.251.15 | VLAN412                   | up   |                |             |
 172.16.251.15 | VLAN999                   | up   |                |             |
172.16.251.15 | VLAN452                   | up   |                |             |
 172.16.251.15 | VLAN450                   | up   |                |             |
 172.16.251.15 | A16                       | up   | 172.16.251.161 | 10          | 1
 172.16.251.15 | Trk1                      | up   | 172.16.251.10  | Trk1        | 1
 172.16.251.15 | A5                        | up   | 172.16.251.170 | 45          | 1
 172.16.251.15 | A6                        | up   | 172.16.251.180 | 45          | 1
 172.16.251.15 | A13                       | up   | 172.16.251.131 | 10          | 1
 172.16.251.15 | A14                       | up   | 172.16.251.141 | 10          | 1
(45 righe)

(END)

**Comment by inphobia** [comment] 2019-03-02 00:52
i'm also seeing the difference when i select a vlan. without a vlan filled in all devices on a location are shown, regardless if they are connected to anything.

with vlan selected, only devices with links are show. devices carrying the selected vlan that are not connected to anything are no longer shown. at first glance this seems to be because of the devicelinks.pm query uses connected vlans only,but i haven't checked in depth yet.


the scenario you are seeing where connected devices aren't showing i haven't been able to reproduce yet.

**Comment by ollyg** [comment] 2019-03-02 20:03
thanks for the bug report! fixed in
[master e7aacddb] #498 Map with VLAN filter omits unconnected devices

**Closed by ollyg** 2019-03-02 20:03 UTC
Labels: bug
