### ISSUE TITLE
uptime incorrect for some devices

### ISSUE THREAD

**Issue by cnoyes72** [netdisco/netdisco#980] opened 2023-02-20 18:40 UTC
Hello,

I've noticed on some of my cisco switches that the device uptime in netdisco is different from what the switch is reporting (including when I poll sysUpTime via snmpwalk).  As a test, I deleted one of the switches in question (pwfltrp7) then did a discover.  While that was happening, I kept doing a "select uptime from device where name ilike '%pwfltrp7%';" and after a bit I saw the correct timeticks displayed (2018133), but shortly after it jumped up (4296988291).  The switch had only been up for a little over 5 hours so the first uptime entry was correct.  This only seems to happen with some older switches (a 3750x in my lab does this also).  

App::Netdisco     2.57.8
SNMP::Info          3.89
DB Schema         75
PostgreSQL         14.00.6
Perl                     5.34.0

**Comment by ollyg** [comment] 2023-03-03 12:12
Hi @cnoyes72 I believe at the moment that this is a duplicate of ticket #981 which I have just fixed and will be in release soon.

The bug is that we were checking non-physical interfaces for their last change time and using this to update the device uptime, but we should only check physical interfaces.

If you upgrade when we release the next version and can reproduce the error, do let me know!

If the bug is still there, please also let me know how much time elapsed between the value setting as 2018133 and then changing to 4296988291 (like seconds, minutes, or hours?). It will be a help to indicate which bit of code is making the change.

**Closed by ollyg** 2023-03-03 12:12 UTC
Labels: assigned-to-project
