### ISSUE TITLE
Can't login with RADIUS

### ISSUE THREAD

**Issue by ubzmrh** [netdisco/netdisco#775] opened 2021-03-08 15:39 UTC
Some instructions seem to be missing in the Netdisco installation manual.

I want to use RADIUS for connection.
I have set up deployement.yml with the appropriate values for my company
`radius:`
`  server: ['93.143.45.12', '93.143.45.13']`
`  secret: 'a very complicated word'`

The RADIUS servers (external) have been configured for my server.

But when I connect, I get this message in netdisco-web.log
`[10211] 2021-03-08 15:07:28 error request to POST /login crashed: Can't open dictionary '/etc/raddb/dictionary' (No such file or directory)`

So, what have I to install to use RADIUS for login ?
My server is RHEL 7.

**Comment by ARK-RAVI** [comment] 2021-03-11 14:23
I have a similar issue today, installed "apt-get install freeradius" with the help of the following suggestion.

https://www.mail-archive.com/netdisco-users@lists.sourceforge.net/msg00831.html

However, there is a new problem reported in netdisco-web.log

Argument "Digest-Attributes" isn't numeric in int at /home/netdisco/perl5/lib/perl5/Authen/Radius.pm line 916.
Argument "User-Name" isn't numeric in int at /home/netdisco/perl5/lib/perl5/Authen/Radius.pm line 916.
Argument "User-Password" isn't numeric in int at /home/netdisco/perl5/lib/perl5/Authen/Radius.pm line 916.
Argument "h323-return-code" isn't numeric in int at /home/netdisco/perl5/lib/perl5/Authen/Radius.pm line 916.

Does anybody encounter this issue earlier do let us know the fix

**Comment by consentfactory** [comment] 2021-03-11 16:10
Having similar issues as well. I'm on RHEL 7 as well, installed freeradius from the same mailing list message as @ARK-RAVI and copied the dictionaries, but having issues still.

Sharing what I sent to the mailing list, I'm receiving an error in Chrome when I log-in with a RADIUS account. The error:

Chrome:
'ERR_INVALID_RESPONSE'

And in the netdisco web log:

netdisco-web.log:
error request to POST /login crashed: Can't call method "add_attributes" on an undefined value at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Auth/Provider/DBIC.pm line 245.

I have verified RADIUS is configured correctly according to the documentation, so I'm at a loss currently. Initially I tried TACACS but that went nowhere (I'm presuming based on RADIUS that I needed to install some dependency, but I don't see documentation for this).

At this point, it kind of seems like a bug, but I can't be certain.

I will happily update the wiki with the required documentation once all of this is resolved.

**Comment by inphobia** [comment] 2021-06-10 00:17
since i don't use radius for netdisco i can't reproduce the issue myself, but we do use https://metacpan.org/pod/Authen::Radius as our radius provider, which seems to require a few steps to get it to work, namely installing freeradius and then a radius dictionary (https://metacpan.org/release/PORTAONE/Authen-Radius-0.32/source/install-radius-db.PL) at the very least.

we have devs using radius, so it does work, but i guess our wiki is missing a few steps to get there.

more errorhandling for missing dictionaries would be welcome it seems. and perhaps https://github.com/netdisco/netdisco/tree/master/share/radius_dictionaries could be fleshed out as well....

**Comment by ubzmrh** [comment] 2021-06-10 11:25
Thanks for the links, they solved my problem.
The necessary `/etc/raddb/dictionary*` files are provided with the `Authen::Radius` module. 
Just download the Authen-Radius-0.32.tar.gz archive from [https://metacpan.org/pod/Authen::Radius](https://metacpan.org/pod/Authen::Radius) and extract the `raddb` directory from the archive, then copy it to `/etc`.

I suggest that these files are included in the Netdisco distribution, along with the installation script. After all, you have included this module in Netdisco.
If you don't want to do this, just add these instructions to the Wiki.

**Comment by ollyg** [comment] 2021-06-23 21:22
have added dictionaries to Netdisco bundle and updated wiki

**Comment by inphobia** [comment] 2021-07-07 19:53
first off: i don't use radius

however, i did have a look at `Authen::Radius` and if i understand it correctly `load_dictionary` should be able to accept a path to where the dictionaries are located.

https://metacpan.org/release/PORTAONE/Authen-Radius-0.32/source/t/local_dictionary.t#L17

perhaps a cleaner approach would be to use `use File::ShareDir 'dist_dir';` and place them under netdisco's share like we do for swagger? (or under ~/environments or something)
this would keep netdisco selfcontained instead of needing /etc & give control over which dictionaries (and their versions) are used.

just an idea, close this issue again if i don't know what i'm talking about 😃 

tagging ppl who might know more about this:
@ollyg 
@rc9000 
@ubzmrh 
@ARK-RAVI

**Comment by ollyg** [comment] 2021-07-14 11:16
thanks, amended in 485cfd24

**Closed by ollyg** 2021-07-14 11:16 UTC
Labels: enhancement
