### ISSUE TITLE
IP Inventory report inconsistent

### ISSUE THREAD

**Issue by danmmby** [netdisco/netdisco#870] opened 2022-05-19 17:54 UTC
## Expected Behavior
reports/ip/ip inventory page would return the IP/DNS information

## Current Behavior
2 issues that I'm having with the IP inventory report.

1. sometimes IPs are missing from the report ( using last 7 days / example: subnet=10.1.50.0/23&daterange=1970-01-01+to+2022-05-19&limit=2048 )
2. reports/ip/ip inventory page sometimes doesn't always return DNS results, the larger the scope we search on the less DNS results it comes back with.

Refreshing the report gives me different results each time.

## Possible Solution

I noticed that if I keep refreshing the page the inconsistent data sometimes is from different "last used" times. In the example recording that I'll link below you can see that on the bottom of the recording on IP 10.1.50.41 & 10.1.50.42 the last used date changes from 4:30 hours to 00:36 minutes. It doesn't have the DNS record attached to 00:36 but it does to 4:30.

## Steps to Reproduce (for bugs)
1. Go to IP reports page.
2. If I look for a /23 subnet as an example and keep "oldest record limit" at the default of 2048. DNS records aren't showing for all of the addresses even though netdisco has all of the DNS records for these addresses.
3. Lowering it to 64 or 32 addresses at max does show more IPs with DNS records, but if you keep refreshing sometimes it shows different results. results are not consistent.

## Context
Trying to pull information from netdisco to use in other tools but the data has to be consistent.

## Your Environment

* Netdisco version used: 2.052005
* SNMP::Info version used: 3.82

## Config info (deployment.yml)

I'm using the default scheduling: 

schedule:
  discoverall:
    when: '5 7 * * *'
  macwalk:
    when:
      min: 20
  arpwalk:
    when:
      min: 50
  nbtwalk:
    when: '0 8,13,21 * * *'
  expire:
    when: '30 23 * * *'

## Device information

No specific device seems to have an issue, it's just the reporting section.

![netdisco-ip-reporting-inconsistencies](https://user-images.githubusercontent.com/105879009/169369063-d3d39fbf-0689-464e-8f89-c5c1046c0fbc.gif)

**Comment by ollyg** [comment] 2022-07-28 21:19
I suspect strongly that this is caused by the result of SQL UNION combined with ORDER BY which did not include the DNS field. Now the DNS field is included in sort, so I am closing the issue.

**Closed by ollyg** 2022-07-28 21:19 UTC
Labels: assigned-to-project

**Comment by danmmby** [comment] 2022-08-02 16:18
> I suspect strongly that this is caused by the result of SQL UNION combined with ORDER BY which did not include the DNS field. Now the DNS field is included in sort, so I am closing the issue.

I updated to the latest version and am not able to replicate the issues I had previously, Thanks for fixing it!!
