### ISSUE TITLE
Port-Channels not showing in netmap

### ISSUE THREAD

**Issue by jaybode** [netdisco/netdisco#428] opened 2018-07-19 17:40 UTC
NOT A BUG - MAYBE EXPECTED BEHAVIOR?

Even when using Manual Device Topology, it appears netmap only shows Ethernet based adjacencies

Wonder if someone can point me to the code  page, so I can change to the filter to show Port-Channels as well when hovering over links. Dancer is very new to me. It maybe actually be a DB query to change I guess.

PS- What fantastic work ! I have been wanting to try Netdisco since version 1, but was recalculated to add PostgreSQL on production server. I found no issues running both MySQL and PostgresSQL with the tuning guide.

**Comment by ollyg** [comment] 2018-12-28 17:52
Hi @jaybode 

Port channels should appear normally on the network map. Are the links also shown as aggregates (channels) in the Device Ports table, with little group icons?

**Comment by inphobia** [comment] 2019-01-12 05:31
seems i can also reproduce this, netdisco HEAD, snmp::info HEAD+ netdisco/snmp-info#296.

device 10.40.72.250 is linked to 10.40.72.251, ports, eth1/20,eth1/27,eth1/28 & po4096.
(also tested by manually linked portchannel4096 between both devices, but that also was a no-go)

device_ports info:

| ip           | port             | descr            | up | up_admin | type           | name                    | mac               | remote_ip    | remote_port      | remote_type | remote_id                       | vlan | pvid | manual_topo | is_uplink | slave_of         | is_master |
|--------------|------------------|------------------|----|----------|----------------|-------------------------|-------------------|--------------|------------------|-------------|---------------------------------|------|------|-------------|-----------|------------------|-----------|
| 10.40.72.250 | Ethernet1/20     | Ethernet1/20     | up | up       | ethernetCsmacd | keepalive link vpc      | 6c:b2:ae:91:19:5e | 169.254.8.2  | Ethernet1/20     | N9K-C9332PQ | d8-n9k2.aquafin.be(FDO21392TF2) | NULL | NULL | False       | True      | NULL             | False     |
| 10.40.72.250 | Ethernet1/27     | Ethernet1/27     | up | up       | ethernetCsmacd | d8-n9k2-trunk           | 6c:b2:ae:91:19:7a | 10.1.100.251 | Ethernet1/27     | N9K-C9332PQ | d8-n9k2.aquafin.be(FDO21392TF2) | 1    | 1    | False       | True      | port-channel4096 | False     |
| 10.40.72.250 | Ethernet1/28     | Ethernet1/28     | up | up       | ethernetCsmacd | d8-n9k2-trunk           | 6c:b2:ae:91:19:7b | 10.1.100.251 | Ethernet1/28     | N9K-C9332PQ | d8-n9k2.aquafin.be(FDO21392TF2) | 1    | 1    | False       | True      | port-channel4096 | False     |
| 10.40.72.250 | port-channel4096 | port-channel4096 | up | up       | ieee8023adLag  | d8-n9k vpc interconnect | 6c:b2:ae:91:19:7a | 10.40.72.251 | port-channel4096 | NULL        | NULL                            | 1    | 1    | False       | True      | NULL             | True      |
| 10.40.72.251 | Ethernet1/20     | Ethernet1/20     | up | up       | ethernetCsmacd | keepalive link vpc      | 6c:b2:ae:91:1c:98 | 169.254.8.1  | Ethernet1/20     | N9K-C9332PQ | d8-n9k1.aquafin.be(FDO21392TFE) | NULL | NULL | False       | True      | NULL             | False     |
| 10.40.72.251 | Ethernet1/27     | Ethernet1/27     | up | up       | ethernetCsmacd | d8-n9k1-trunk           | 6c:b2:ae:91:1c:b4 | 10.1.100.250 | Ethernet1/27     | N9K-C9332PQ | d8-n9k1.aquafin.be(FDO21392TFE) | 1    | 1    | False       | True      | port-channel4096 | False     |
| 10.40.72.251 | Ethernet1/28     | Ethernet1/28     | up | up       | ethernetCsmacd | d8-n9k1-trunk           | 6c:b2:ae:91:1c:b5 | 10.1.100.250 | Ethernet1/28     | N9K-C9332PQ | d8-n9k1.aquafin.be(FDO21392TFE) | 1    | 1    | False       | True      | port-channel4096 | False     |
| 10.40.72.251 | port-channel4096 | port-channel4096 | up | up       | ieee8023adLag  | d8-n9k vpc interconnect | 6c:b2:ae:91:1c:b4 | 10.40.72.250 | port-channel4096 | NULL        | NULL                            | 1    | 1    | False       | True      | NULL             | True      |



remote_id is missing for the portchannel interfaces, but neither via snmp or on cli do the portchannel interfaces return cdp or lldp neighbor info.



map shows:
![image](https://user-images.githubusercontent.com/39005454/51069539-7a258a80-1631-11e9-94dc-8fbb4bef97cd.png)

ports shows:
![image](https://user-images.githubusercontent.com/39005454/51069551-ba850880-1631-11e9-969f-258771316ae8.png)



also tested on 4.020002, but there 1 of the 2 devices is missing remote_port for portchannel4096, guess due to 7811c321470fe9c78d102dd91eef934e9e654af2 only being in HEAD. never paid much attention to it since we use nexus vpc all over the place, which might make portchannel info a bit more funky.

**Comment by ollyg** [comment] 2019-03-02 21:54
Hi @jaybode this is fixed in patch:
[master a643820a] #428 Port-Channels not showing in netmap

and will be in the next release.

**Closed by ollyg** 2019-03-02 21:54 UTC
Labels: bug

**Comment by jaybode** [comment] 2019-08-30 18:36
Just a comment, I know this is old and now closed.

I never got a chance to thank you promptly since I originally posted this issue on incorrect GITHUB account.

You guys are awesome for supporting such a project!! Please keep up the excellent work.

You should put up a small paypal or donation link. I personal would like to drop in a few dollars, and hope others will do the same.

Cheers,

Jason

**Comment by inphobia** [comment] 2019-08-30 19:45
you're welcome. personally i do this more as a hobby, but if you want to make a donation just make it out to whatever charity you feel like. i think i speak for most devs when saying this.
