### ISSUE TITLE
Feature request: select depth in neighbourmap

### ISSUE THREAD

**Issue by pioevogel** [netdisco/netdisco#690] opened 2019-12-17 10:34 UTC
Hi,

Right now it's only possible to select on of these three views:

1. Full map
2. Map with direct neigbours
3. All carrying a certain vlan

I would really like a 4th: map with neighbours and neighbours of those, configurable with a depth value. So a value of 1 is equal to option 2 in the list above, a value of 2 also gives the neighbours of those neighbours and so on.

In a large network this will really help looking at a specific area.

**Comment by ollyg** [comment] 2019-12-23 08:21
duplicate of #620

**Closed by ollyg** 2019-12-23 08:21 UTC
Labels: duplicate, wishlist
