### ISSUE TITLE
Neighbors on maps with one-side info only randomly skipped

### ISSUE THREAD

**Issue by Linwood-F** [netdisco/netdisco#436] opened 2018-08-27 02:08 UTC
We have a bunch of AP's (Aerohives) that do LLDP just fine, but apparently their neighbor information is not visible in the SNMP requests from them, at least it does not appear in the ports list.

On the other hand, it conveys that information to the connected device (Cisco switches in this case) just fine.

What happens is the query in DeviceLinks.pm checks the left IP against the right to avoid duplicates. The result is that randomly, the neighbor display works, or fails, depending on whether the AP happens to be on the left, or on the right.

Ideally this might be fixed by putting the relevant data from the AP's, but no idea if that's even possible in their SNMP responses.  A simple fix, however, appears to be to choose a different way to tell which to pick -- use the resulting port's existence for a comparison, so that if one is null, you always pick the other.  At least it seems to work -- in a few hundred nodes I see no bad effects so far.

## Expected Behavior

Ideally, chose the left/right side from the pair which has the most info, rather than (effectively) randomly based on IP.

## Current Behavior
Chosen by the bigger IP.

## Possible Solution

In the SQL, remove the IP comparison, and add a HAVING statement on the port info as below.  I'm not all that comfortable at the various alternatives of having an array as a comparison, but this does seem to work.  Maybe there's a better comparison, like the name

```
 WHERE dp.remote_port IS NOT NULL
   AND dp.port !~* 'vlan'
   AND (dp.descr IS NULL OR dp.descr !~* 'vlan')
   AND (dp.type IS NULL OR dp.type !~* '^(53|ieee8023adLag|propVirtual|l2vlan|l3ipvlan|135|136|137)\$')
   AND (dp.is_master = 'false' OR dp.slave_of IS NOT NULL)
--   AND dp.ip <= di.ip
 GROUP BY left_ip, left_dns, left_name, right_ip, right_dns, right_name
	having array_agg(dp.port) <= array_agg(dp.remote_port)
 ORDER BY dp.ip
```

## Steps to Reproduce (for bugs)

I have no idea how to reproduce this outside of having this gear, but here is some output that may help understand.

Two AP's are 10.108.1.214 (d8:54:a2:9d:69:40) and 10.108.1.224 (88:5b:dd:57:df:c0).  When I run 

```
$ ~netdisco/bin/netdisco-do show -d 10.108.1.214 -e c_id
[56291] 2018-08-27 01:54:07  info App::Netdisco version 2.039031 loaded.
[56291] 2018-08-27 01:54:08  info show: [10.108.1.214]/c_id started at Sun Aug 26 20:54:08 2018
undef
[56291] 2018-08-27 01:54:20  info show: finished at Sun Aug 26 20:54:20 2018
[56291] 2018-08-27 01:54:20  info show: status done: Showed c_id response from 10.108.1.214
```

These are connected, respectively, to switches at 10.108.1.2 and 192.168.168.2.  When I run the same for them:

```
$ ~netdisco/bin/netdisco-do show -d 10.108.1.2 -e c_id
[61982] 2018-08-27 01:54:43  info App::Netdisco version 2.039031 loaded.
[61982] 2018-08-27 01:54:43  info show: [10.108.1.2]/c_id started at Sun Aug 26 20:54:43 2018
\ {
   stuff...
    0.2.13    "d8:54:a2:9d:69:40",
   more stuff...
}
```

```
~$ ~netdisco/bin/netdisco-do show -d 10.108.1.1 -e c_id
[3723] 2018-08-27 01:55:20  info App::Netdisco version 2.039031 loaded.
[3723] 2018-08-27 01:55:20  info show: [192.168.168.2]/c_id started at Sun Aug 26 20:55:20 2018
\ {
    stuff...(lots of it)
    0.143.82   "88:5b:dd:57:df:c0",
   stuff....
}
[3723] 2018-08-27 01:55:27  info show: finished at Sun Aug 26 20:55:27 2018
[3723] 2018-08-27 01:55:27  info show: status done: Showed c_id response from 192.168.168.2
```

The first of these (10.108.1.214) works, but the second (10.108.1.224) does not, solely due to the luck of the draw in comparing against the associated neighbor IP as best I can tell.

## Context

We have about 200 AP's, and this causes 95 of them not to show neighbor informaiton.  

## Your Environment
Almost all cisco, various switches.
Aerohive AP's
Netdisco 2.39.31
Ubuntu 18.04.01
SNMP 3.61
Postgresql 10.00.4
Perl 5.26.1

**Comment by inphobia** [comment] 2018-08-27 08:25
we're seeing the same thing:
(output cleaned up somewhat)

switch side:

#sh lldp neighbors
Capability codes:
    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID           Local Intf     Hold-time  Capability      Port ID
HiveAP212           Gi1/0/45       61         B,W             mgt0

hiveap side:

HiveAP212#sh lldp neighbor
LLDP neighbor table: Total number = 1
--------------------------------
Incoming Port: eth0
Chassis ID(mac address): 
Port ID(interface name): Gi1/0/45
Hold time(seconds): 102
System name: 
System description: Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Wed 09-Apr-14 02:55 by prod_rel_team



i think the important part here is that the cisco side reports interface mgt0 for the access point, while the access point reports eth0 as receiving interface.

the netdisco mapping faq mentions that this is not supported (interface names must match) so i left it at that.

**Comment by Linwood-F** [comment] 2018-08-27 12:52
@inphobia I see that (now), but the query I referenced does not appear to enforce that requirement.  That some of the aerohives (for us) appear and some do not would also seem to discount it somewhat.

I think the query is asymmetric in the tests for each pair (pair being a->b and b->a).  It needs to find the port on the right side that it has received in the LLD poll on the left, it doesn't appear to try to match that the right side at the same time to see that it sees the left the same way.

Perhaps a better example of that lack of symmetry is in the test (in the code as written) for dp.ip <= di.ip.  If I ran it with the code as written I get 368 rows (it's 367 if equality is excluded which I I think is because we have a loop on one device).   If I remove the test entirely it is 687 rows, not the 736 you would expect if all the tests were applied equally to left and right side.

I don't think the Aerohive issue (at least for us) is lack of matching ports, it's lack of any ports being returned by SNMP from the LLDP status in the aerohive itself (does yours show any with the debug statement in my original post?).  So far from not matching on eth0 vs. mgmt, I don't think it has any remote port info (i.e. identifying the cisco) from the aerohive at all.  This means in the query it finds the aerohive when it's on the right side of the query, but not when it's on the left.  And that's OK -- except that the dp.ip <= di.ip presumes it will have found it both times, and it doesn't. 

That's why I think a more specific test here would be better to eliminate the pair based on whether it finds something, not just the device IP.

Try changing the query, see if all your aerohives don't appear (and look and see if anything bad does appear).

**Comment by Linwood-F** [comment] 2018-08-27 13:02
Actually you made me take another look, and I'm not convinced this test is complete either.  It does resurrect the missing items, but I think it may be either including some duplicates or omitting.  I need to look further for a better test.  I am still sure the existing test is eliminating too much, the trick is to prune duplicates without pruning non-duplicates.

**Comment by Linwood-F** [comment] 2018-08-27 15:09
Here's an alternative proposal that goes more directly to the problem, the aggregate comparison was more accident I think.  This forms the result set with duplicates, then explicitly eliminates them.  It does it similarly to the current query (on IP) so the result set from this and the other should be the same otherwise, except for some new inclusions that were one side.

Except: I could not find a case of this in my testing, but at least in principle if the port names are different as seen from each side, this might leave duplicates in.  I would argue a duplicate (that is really duplicated only by different port name abbreviations) is better than an omission.  The former is obvious when viewed by a human, the latter (the omission) is much harder to figure out.

Note the code is essentially as before omitting the left/right IP comparison, but packaged up as a CTE and used in the result and the existence check:

`''
__PACKAGE__->result_source_instance->view_definition(<<ENDSQL
With BothWays as
(
         SELECT dp.ip AS left_ip, ld.dns AS left_dns, ld.name AS left_name,
                        array_agg(dp.port) AS left_port, array_agg(dp.name) AS left_descr,
                        sum( COALESCE(dpp.raw_speed,0) ) as aggspeed,
                        count(*) AS aggports,
                        di.ip AS right_ip, rd.dns AS right_dns, rd.name AS right_name,
                        array_agg(dp.remote_port) AS right_port, array_agg(dp2.name) AS right_descr

         FROM device_port dp
         LEFT OUTER JOIN device_port_properties dpp USING (ip, port)
         INNER JOIN device ld ON dp.ip = ld.ip
         INNER JOIN device_ip di ON dp.remote_ip = di.alias
         INNER JOIN device rd ON di.ip = rd.ip
         LEFT OUTER JOIN device_port dp2
           ON (di.ip = dp2.ip
                   AND ((dp.remote_port = dp2.port)
                                OR (dp.remote_port = dp2.name)
                                OR (dp.remote_port = dp2.descr)))

         WHERE dp.remote_port IS NOT NULL
           AND dp.port !~* 'vlan'
           AND (dp.descr IS NULL OR dp.descr !~* 'vlan')
           AND (dp.type IS NULL OR dp.type !~* '^(53|ieee8023adLag|propVirtual|l2vlan|l3ipvlan|135|136|137)\$')
           AND (dp.is_master = 'false' OR dp.slave_of IS NOT NULL)
         GROUP BY left_ip, left_dns, left_name, right_ip, right_dns, right_name
)
select *
from BothWays b
where not exists
        (
                select *
                from BothWays b2
                where b2.right_ip = b.left_ip and b2.right_port = b.left_port and b2.left_ip < b.left_ip
        )
ORDER BY 1, 2
ENDSQL

''`

**Comment by inphobia** [comment] 2018-08-28 22:38
excellent remark , i hadnt considered checking if hiveos would actually respond to those iod's. seems my access points return "undef" when testing for hasCDP or lldp_sys_cap. we have around 150 deployed , and at first glace for some reason 10 - 20 or so do actually find their neighbours, but i havent found a reason why.

```
%%% netdisco-do show -d 10.1.1.130 -e lldp_sys_cap
[23180] 2018-08-28 22:13:51  info App::Netdisco version 2.039031 loaded.
[23180] 2018-08-28 22:13:51  info show: [10.1.1.130]/lldp_sys_cap started at Wed Aug 29 00:13:51 2018
undef
[23180] 2018-08-28 22:13:52  info show: finished at Wed Aug 29 00:13:52 2018
[23180] 2018-08-28 22:13:52  info show: status done: Showed lldp_sys_cap response from 10.1.1.130

%%% netdisco-do show -d 10.1.1.130 -e hasCDP
[23183] 2018-08-28 22:13:59  info App::Netdisco version 2.039031 loaded.
[23183] 2018-08-28 22:13:59  info show: [10.1.1.130]/hasCDP started at Wed Aug 29 00:13:59 2018
undef
[23183] 2018-08-28 22:14:00  info show: finished at Wed Aug 29 00:14:00 2018
[23183] 2018-08-28 22:14:00  info show: status done: Showed hasCDP response from 10.1.1.130
```


we do have a kinda convoluted setup where our sites have 2 vrf's. i didnt really pay much attention to it since the wiki has some warnings around vrf's (and nx-os, but it says it applies globally) and making pretty maps is somewhere at the bottom of my todo list atm.

if you can whip up a diff i'll have a try on our testsetup.

##### shameless plug: i'm currently working on adding hiveos support to rancid, code is here if you are interested: [https://github.com/inphobia/rancid-aerohive-support](url)

**Comment by Linwood-F** [comment] 2018-08-31 00:27
I don't actually support the Aerohives as in configuration, but it took me about a dozen requests and a lot of false starts to get them to consistently enable LLDP.  I'm not sure they ever got CDP working right. For reasons unclear LLDP would work on half of them, but didn't seem to "stick" on others, by site -- telling me it was something they were doing wrong.

I'm not sure what you mean by a diff, for the SQL Above?   It's a complete replacement of the SQL, but here's a diff file.  I have no idea why the prologue comments are coming out, I didn't think I changed them, but it should be reasonably clear.

I've been experimenting with this for a couple days now on two different sites, one complicated and one largish (500 cisco devices, which I think as large).  So far I haven't found anything it mis-represented, though I do anticipate it might incorrectly report some cases where dumb hubs are used, which might propagate LLDP or CDP.  But one case (not a dumb hub but a dumb microwave mesh) did not.

But with this, and with LLDP finally turned on for the Aerohives, they all show their proper connection now.

```
--- DeviceLinks.original        2018-08-30 19:19:46.860203588 -0500
+++ /home/netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/Virtual/DeviceLinks.pm        2018-08-28 21:06:26.035679885 -0500
@@ -8,39 +8,47 @@
 __PACKAGE__->table_class('DBIx::Class::ResultSource::View');

 # note to future devs:
-# this query does not use the slave_of field in device_port table to group
-# ports because what we actually want is total b/w between devices on all
-# links, regardless of whether those links are in an aggregate.
+# this query does not use the slave_of field in device_port table to group
+# ports because what we actually want is total b/w between devices on all
+# links, regardless of whether those links are in an aggregate.

 __PACKAGE__->table('device_links');
 __PACKAGE__->result_source_instance->is_virtual(1);
 __PACKAGE__->result_source_instance->view_definition(<<ENDSQL
- SELECT dp.ip AS left_ip, ld.dns AS left_dns, ld.name AS left_name,
-        array_agg(dp.port) AS left_port, array_agg(dp.name) AS left_descr,
-        sum( COALESCE(dpp.raw_speed,0) ) as aggspeed,
-        count(*) AS aggports,
-        di.ip AS right_ip, rd.dns AS right_dns, rd.name AS right_name,
-        array_agg(dp.remote_port) AS right_port, array_agg(dp2.name) AS right_descr
-
- FROM device_port dp
- LEFT OUTER JOIN device_port_properties dpp USING (ip, port)
- INNER JOIN device ld ON dp.ip = ld.ip
- INNER JOIN device_ip di ON dp.remote_ip = di.alias
- INNER JOIN device rd ON di.ip = rd.ip
- LEFT OUTER JOIN device_port dp2
-   ON (di.ip = dp2.ip
-       AND ((dp.remote_port = dp2.port)
-            OR (dp.remote_port = dp2.name)
-            OR (dp.remote_port = dp2.descr)))
-
- WHERE dp.remote_port IS NOT NULL
-   AND dp.port !~* 'vlan'
-   AND (dp.descr IS NULL OR dp.descr !~* 'vlan')
-   AND (dp.type IS NULL OR dp.type !~* '^(53|ieee8023adLag|propVirtual|l2vlan|l3ipvlan|135|136|137)\$')
-   AND (dp.is_master = 'false' OR dp.slave_of IS NOT NULL)
-   AND dp.ip <= di.ip
- GROUP BY left_ip, left_dns, left_name, right_ip, right_dns, right_name
- ORDER BY dp.ip
+With BothWays as
+(
+         SELECT dp.ip AS left_ip, ld.dns AS left_dns, ld.name AS left_name,
+                        array_agg(dp.port) AS left_port, array_agg(dp.name) AS left_descr,
+                        sum( COALESCE(dpp.raw_speed,0) ) as aggspeed,
+                        count(*) AS aggports,
+                        di.ip AS right_ip, rd.dns AS right_dns, rd.name AS right_name,
+                        array_agg(dp.remote_port) AS right_port, array_agg(dp2.name) AS right_descr
+         FROM device_port dp
+         LEFT OUTER JOIN device_port_properties dpp USING (ip, port)
+         INNER JOIN device ld ON dp.ip = ld.ip
+         INNER JOIN device_ip di ON dp.remote_ip = di.alias
+         INNER JOIN device rd ON di.ip = rd.ip
+         LEFT OUTER JOIN device_port dp2
+           ON (di.ip = dp2.ip
+                   AND ((dp.remote_port = dp2.port)
+                                OR (dp.remote_port = dp2.name)
+                                OR (dp.remote_port = dp2.descr)))
+         WHERE dp.remote_port IS NOT NULL
+           AND dp.port !~* 'vlan'
+           AND (dp.descr IS NULL OR dp.descr !~* 'vlan')
+           AND (dp.type IS NULL OR dp.type !~* '^(53|ieee8023adLag|propVirtual|l2vlan|l3ipvlan|135|136|137)\$')
+           AND (dp.is_master = 'false' OR dp.slave_of IS NOT NULL)
+         GROUP BY left_ip, left_dns, left_name, right_ip, right_dns, right_name
+)
+select *
+from BothWays b
+where not exists
+        (
+                select *
+                from BothWays b2
+                where b2.right_ip = b.left_ip and b2.right_port = b.left_port and b2.left_ip < b.left_ip
+        )
+ORDER BY 1, 2
 ENDSQL
 );
```

**Comment by inphobia** [comment] 2018-09-07 20:43
that patch works pretty nice, all my aerohive devices now show up where i am expecting them.

vmware esx & cisco ucs still is a no go, but i'll look into that some other time.

**Comment by inphobia** [comment] 2018-10-14 13:57
actually, after giving it some time vmware esx (seems not to report it's ip in cdp/lldp) and cisco ucs blade chassis seem to work too.

**Comment by inphobia** [comment] 2018-10-26 20:51
been running this for over 6 weeks without noticing any regressions.

3 device classes do not work:
 * citrix netscalers (detected as layer4+7 device)
 * fortinet firewalls (mine are not running lldp, so makes sence i guess)
 * exinda/gfi traffic shapers (no snmp::info module yet, detected as layer 4+7 but is actually layer 2 device). 

all of these did not work before either.

**Comment by Linwood-F** [comment] 2018-10-27 02:17
Glad to hear it is working for you; it also is for me, though I have one anomaly I have yet to figure out, where one (only one) device is connected WAY out of place.  I'm not sure if it is this, or something weird in the network.  I'll try to dig into it this coming week.  Otherwise, this has worked well for me.

**Comment by inphobia** [comment] 2018-11-28 00:41
@ollyg &  @JeroenvIS

could this perhaps be considered for inclusion?

if you don't think this should be the default setting perhaps an option "lazy_matching" could be included to use this query? this makes our aerohive (switch sees eth0, aerohive reports mgmt0 as lldp source) & vmware/cisco ucs devices (seems they report 0.0.0.0 as ip, could be fixed in latest vmware patches) match their neighbours.

we have not noticed any regressions either.

**Comment by ollyg** [comment] 2019-01-02 20:37
[master d614382f] #436 new SQL query for neigbor map to allow mismatched/one-way links (Linwood-F)

**Comment by ollyg** [comment] 2019-01-02 20:37
Many thanks!

**Closed by ollyg** 2019-01-02 20:37 UTC
Labels: bug

**Comment by inphobia** [comment] 2019-01-02 21:02
have been running with this for 3 months and not seen any regressions.


2 side notes which might or might not be related:

1) with this patch we finally see our vmware esx's running on cisco blades in our topology, but snmp::info or netdisco (most likely snmp::info) is making up nonexisting mac addresses for the vmware servers. notice how the cisco ucs interconnects report `54:7f:ee:85:ab:c0` but that's nowhere to be found on vmware. but vmware's snmp setup is weird.
```

netdisco-do psql -e "select ip,port,name,mac,remote_ip,remote_port,remote_type,vlan,pvid,is_uplink,manual_topo from device_port where remote_ip = '10.40.254.163'"
[27401] 2019-01-02 20:57:15  info App::Netdisco version 2.040002 loaded.
[27401] 2019-01-02 20:57:15  info psql:  started at Wed Jan  2 21:57:15 2019
      ip       |     port      |              name              |        mac        |   remote_ip   |    remote_port    | remote_type | vlan | pvid | is_uplink | manual_topo
---------------+---------------+--------------------------------+-------------------+---------------+-------------------+-------------+------+------+-----------+-------------
 10.40.254.141 | Vethernet2367 | server 2/5, VNIC esx-dvs-lan-a | 54:7f:ee:85:ab:c0 | 10.40.254.163 | 76:6d:6e:69:63:36 | VMware ESX  | 1    |    1 | t         | f
 10.40.254.142 | Vethernet2368 | server 2/5, VNIC esx-dvs-lan-b | 54:7f:ee:83:45:e0 | 10.40.254.163 | 76:6d:6e:69:63:37 | VMware ESX  | 1    |    1 | t         | f
(2 rows)


netdisco-do psql -e "select * from device_port where ip = '10.40.254.163'"
      ip       |                                                  port                                                  |         creation          |                                                 descr                                                  | up | up_admin |       type       | duplex | duplex_admin |  speed  |      name      |        mac        | mtu  | stp | remote_ip | remote_port | remote_type | remote_id | vlan | pvid | lastchange | manual_topo | is_uplink |                                               slave_of                                                | is_master
---------------+--------------------------------------------------------------------------------------------------------+---------------------------+--------------------------------------------------------------------------------------------------------+----+----------+------------------+--------+--------------+---------+----------------+-------------------+------+-----+-----------+-------------+-------------+-----------+------+------+------------+-------------+-----------+-------------------------------------------------------------------------------------------------------+-----------
 10.40.254.163 | Virtual interface: vmk20 on vswitch vSwitch1 portgroup: datastore network                              | 2019-01-02 19:12:00.98074 | Virtual interface: vmk20 on vswitch vSwitch1 portgroup: datastore network                              | up | up       | vmwareVirtualNic |        |              | 0       | vmk20-vSwitch1 | 00:50:56:60:ed:21 | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Distributed Virtual VMware switch: DvsPortset-0                                                        | 2019-01-02 19:12:00.98074 | Distributed Virtual VMware switch: DvsPortset-0                                                        | up | up       | propMultiplexor  |        |              | 0       | DvsPortset-0   | 00:00:00:00:00:00 | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic2 at 08:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic2 at 08:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 08:00.0        | 00:25:b5:10:11:9f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic7 at 13:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic7 at 13:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 13:00.0        | 00:25:b5:10:20:7f | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic3 at 09:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic3 at 09:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 09:00.0        | 00:25:b5:10:20:9f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic5 at 11:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic5 at 11:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 11:00.0        | 00:25:b5:10:20:6f | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Link Aggregation Management Network on switch: vSwitch0, load balancing algorithm: source port id hash | 2019-01-02 19:12:00.98074 | Link Aggregation Management Network on switch: vSwitch0, load balancing algorithm: source port id hash | up | up       | ieee8023adLag    |        |              | 20 Gbps | vSwitch0       | 00:25:b5:10:11:8f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic4 at 10:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic4 at 10:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 10:00.0        | 00:25:b5:10:11:6f | 1500 |     |           |             |             |           |      |      |          0 | f           |           | Link Aggregation sys_servers_local on switch: vSwitch0, load balancing algorithm: source port id hash | f
 10.40.254.163 | Link Aggregation vmotion on switch: vSwitch0, load balancing algorithm: source port id hash            | 2019-01-02 19:12:00.98074 | Link Aggregation vmotion on switch: vSwitch0, load balancing algorithm: source port id hash            | up | up       | ieee8023adLag    |        |              | 20 Gbps | vSwitch0       | 00:25:b5:10:20:8f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Link Aggregation sys_servers_local on switch: vSwitch0, load balancing algorithm: source port id hash  | 2019-01-02 19:12:00.98074 | Link Aggregation sys_servers_local on switch: vSwitch0, load balancing algorithm: source port id hash  | up | up       | ieee8023adLag    |        |              | 20 Gbps | vSwitch0       | 00:25:b5:10:11:8f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | t
 10.40.254.163 | Device vmnic0 at 06:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic0 at 06:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 06:00.0        | 00:25:b5:10:11:8f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic1 at 07:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic1 at 07:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 07:00.0        | 00:25:b5:10:20:8f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Distributed Virtual VMware switch: DvsPortset-1                                                        | 2019-01-02 19:12:00.98074 | Distributed Virtual VMware switch: DvsPortset-1                                                        | up | up       | propMultiplexor  |        |              | 0       | DvsPortset-1   | 00:00:00:00:00:00 | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Traditional Virtual VMware switch: vSwitch0                                                            | 2019-01-02 19:12:00.98074 | Traditional Virtual VMware switch: vSwitch0                                                            | up | up       | propMultiplexor  |        |              | 0       | vSwitch0       | 00:00:00:00:00:00 | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Link Aggregation vca-ha on switch: vSwitch0, load balancing algorithm: source port id hash             | 2019-01-02 19:12:00.98074 | Link Aggregation vca-ha on switch: vSwitch0, load balancing algorithm: source port id hash             | up | up       | ieee8023adLag    |        |              | 20 Gbps | vSwitch0       | 00:25:b5:10:11:8f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Virtual interface: vmk0 on vswitch vSwitch0 portgroup: Management Network                              | 2019-01-02 19:12:00.98074 | Virtual interface: vmk0 on vswitch vSwitch0 portgroup: Management Network                              | up | up       | vmwareVirtualNic |        |              | 0       | vmk0-vSwitch0  | 00:50:56:6d:61:65 | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Link Aggregation datastore network on switch: vSwitch1, load balancing algorithm: source port id hash  | 2019-01-02 19:12:00.98074 | Link Aggregation datastore network on switch: vSwitch1, load balancing algorithm: source port id hash  | up | up       | ieee8023adLag    |        |              | 20 Gbps | vSwitch1       | 00:25:b5:10:11:9f | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Traditional Virtual VMware switch: vSwitch1                                                            | 2019-01-02 19:12:00.98074 | Traditional Virtual VMware switch: vSwitch1                                                            | up | up       | propMultiplexor  |        |              | 0       | vSwitch1       | 00:00:00:00:00:00 | 9000 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
 10.40.254.163 | Device vmnic6 at 12:00.0 nenic                                                                         | 2019-01-02 19:12:00.98074 | Device vmnic6 at 12:00.0 nenic                                                                         | up | up       | ethernetCsmacd   |        |              | 20 Gbps | 12:00.0        | 00:25:b5:10:11:7f | 1500 |     |           |             |             |           |      |      |          0 | f           |           |                                                                                                       | f
(19 rows)


```

i also noticed a device looped back to itself today, but that might be the actual situation onsite:

```
netdisco-do psql -e "select ip,port,name,mac,remote_ip,remote_port,remote_type,vlan,pvid,is_uplink,manual_topo from device_port where remote_ip = '10.91.100.1'"
[27353] 2019-01-02 20:52:08  info App::Netdisco version 2.040002 loaded.
[27353] 2019-01-02 20:52:08  info psql:  started at Wed Jan  2 21:52:08 2019
     ip      |     port      | name |        mac        |  remote_ip  |  remote_port  | remote_type | vlan | pvid | is_uplink | manual_topo
-------------+---------------+------+-------------------+-------------+---------------+-------------+------+------+-----------+-------------
 10.91.100.1 | FastEthernet1 | Fa1  | 00:22:90:1f:a2:f3 | 10.91.100.1 | FastEthernet3 | Cisco 877   | 1    |    1 | t         | f
 10.91.100.1 | FastEthernet3 | Fa3  | 00:22:90:1f:a2:f5 | 10.91.100.1 | FastEthernet1 | Cisco 877   | 1    |    1 | t         | f
(2 rows)

```
