### ISSUE TITLE
 Search failed! Please contact your site administrator.

### ISSUE THREAD

**Issue by jacobghattas** [netdisco/netdisco#758] opened 2020-12-29 07:23 UTC
Getting the "Search failed! Please contact your site administrator."
after having upgraded to 2.047.
on all admin operations.

![image](https://user-images.githubusercontent.com/53054419/103265928-6c50a780-49b7-11eb-9305-0133674ecdc1.png)
![image](https://user-images.githubusercontent.com/53054419/103265937-7377b580-49b7-11eb-98a5-a8593a9775ba.png)

**Comment by ollyg** [comment] 2020-12-29 08:29
Hi @jacobghattas 
Unfortunately I can't reproduce this issue. Can you stop the web service (netdisco-web) and restart it in the foreground using this command, and then when the failed message appears, see if there's an error given?

`plackup -R share,lib,~/environments bin/netdisco-web-fg`

If you don't see anything obvious, try this instead (adds database logging):

`DBIC_TRACE=1 plackup -R share,lib,~/environments bin/netdisco-web-fg`

thanks

**Comment by lupin3rd** [comment] 2020-12-29 08:36
Same error after the upgrade to 2.47.0!

Error:
netdisco@netdisco:~$ ~/bin/localenv starman bin/netdisco-web-fg --workers=1 --disable-keepalive
2020/12/29-09:33:37 Starman::Server (type Net::Server::PreFork) starting! pid(1726)
Resolved [*]:5000 to [::]:5000, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 5000 on host :: with IPv6
Setting gid to "1000 1000 1000"
[1727] 2020-12-29 08:33:38  warn App::Netdisco 2.047000 web
Odd number of elements in anonymous hash at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 287.
[1727] 2020-12-29 08:33:54 error request to GET /ajax/content/admin/jobqueue crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  syntax error at or near "0"
LINE 1: ...e target ON target.ip = me.device WHERE ( ( ARRAY(0x55b85e8e...
                                                             ^ [for Statement "SELECT me.job, me.entered, me.started, me.finished, me.device, me.port, me.action, me.subaction, me.status, me.username, me.userip, me.log, me.debug, me.device_key, to_char(entered, 'YYYY-MM-DD HH24:MI'), to_char(finished, 'YYYY-MM-DD HH24:MI'), to_char(started, 'YYYY-MM-DD HH24:MI'), target.ip, target.creation, target.dns, target.description, target.uptime, target.contact, target.name, target.location, target.layers, target.num_ports, target.mac, target.serial, target.model, target.ps1_type, target.ps2_type, target.ps1_status, target.ps2_status, target.fan, target.slots, target.vendor, target.os, target.os_ver, target.log, target.snmp_ver, target.snmp_comm, target.snmp_class, target.snmp_engineid, target.vtp_domain, target.last_discover, target.last_macsuck, target.last_arpnip FROM admin me LEFT JOIN device target ON target.ip = me.device WHERE ( ( ARRAY(0x55b85e8efa00) IS NULL AND HASH(0x55b85e7673d0) = ? ) ) ORDER BY entered DESC, device DESC, action DESC LIMIT ?" with ParamValues: 1='-or', 2='50'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 287

**Comment by jacobghattas** [comment] 2020-12-29 09:42
Thank you Oliver...
Adding the outputs :)


[netdisco@netlogdbgsrv ~]$ plackup -R share,lib,~/environments bin/netdisco-web-fg
Watching share lib ~/environments bin/netdisco-web-fg for file updates.
[1535] 2020-12-29 09:37:57  warn App::Netdisco 2.047000 web
HTTP::Server::PSGI: Accepting connections at http://0:5000/
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET / HTTP/1.1" 200 17729 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /javascripts/dataTables.ip-address-detect.js HTTP/1.1" 200 411 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/bootstrap.min.css HTTP/1.1" 200 124439 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/bootstrap2-toggle.min.css HTTP/1.1" 200 1705 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/jquery.qtip.min.css HTTP/1.1" 200 9203 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/awesome-bootstrap-checkbox.css HTTP/1.1" 200 9097 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/smoothness/jquery-ui.custom.min.css HTTP/1.1" 200 16879 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/font-awesome.min.css HTTP/1.1" 200 22084 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/toastr.css HTTP/1.1" 200 5558 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/d3-force-network-chart.css HTTP/1.1" 200 4661 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/netdisco.css HTTP/1.1" 200 15202 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/bootstrap-tree.css HTTP/1.1" 200 1326 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/daterangepicker-bs2.css HTTP/1.1" 200 5194 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/dataTables.bootstrap.css HTTP/1.1" 200 5643 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /css/nd_print.css HTTP/1.1" 200 350 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /images/navbar_disco.png HTTP/1.1" 200 12328 "http://10.251.8.170:5000/css/netdisco.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:08 +0200] "GET /images/favicon.ico HTTP/1.1" 200 1150 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:12 +0200] "POST /admin/discoverall HTTP/1.1" 302 0 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:13 +0200] "GET /admin/jobqueue HTTP/1.1" 200 22922 "http://10.251.8.170:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
10.250.185.185 - - [29/Dec/2020:11:38:13 +0200] "GET /images/favicon.ico HTTP/1.1" 200 1150 "http://10.251.8.170:5000/admin/jobqueue" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
Odd number of elements in anonymous hash at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 287.
[1535] 2020-12-29 09:38:13 error request to GET /ajax/content/admin/jobqueue crashed: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  syntax error at or near "0"
LINE 1: ...e target ON target.ip = me.device WHERE ( ( ARRAY(0x6d5b280)...
                                                             ^ [for Statement "SELECT me.job, me.entered, me.started, me.finished, me.device, me.port, me.action, me.subaction, me.status, me.username, me.userip, me.log, me.debug, me.device_key, to_char(entered, 'YYYY-MM-DD HH24:MI'), to_char(finished, 'YYYY-MM-DD HH24:MI'), to_char(started, 'YYYY-MM-DD HH24:MI'), target.ip, target.creation, target.dns, target.description, target.uptime, target.contact, target.name, target.location, target.layers, target.num_ports, target.mac, target.serial, target.model, target.ps1_type, target.ps2_type, target.ps1_status, target.ps2_status, target.fan, target.slots, target.vendor, target.os, target.os_ver, target.log, target.snmp_ver, target.snmp_comm, target.snmp_class, target.snmp_engineid, target.vtp_domain, target.last_discover, target.last_macsuck, target.last_arpnip FROM admin me LEFT JOIN device target ON target.ip = me.device WHERE ( ( ARRAY(0x6d5b280) IS NULL AND HASH(0x6db3650) = ? ) ) ORDER BY entered DESC, device DESC, action DESC LIMIT ?" with ParamValues: 1='-or', 2='50'] at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 287
10.250.185.185 - - [29/Dec/2020:11:38:13 +0200] "GET /ajax/content/admin/jobqueue? HTTP/1.1" 500 510 "http://10.251.8.170:5000/admin/jobqueue" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"




####################################################


[netdisco@netlogdbgsrv ~]$ DBIC_TRACE=1 plackup -R share,lib,~/environments bin/netdisco-web-fg


SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note
  FROM users me
WHERE me.username ILIKE 'Jacob'
SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note
  FROM users me
WHERE me.username ILIKE 'Jacob'
SELECT me.role
  FROM (
    SELECT username, 'port_control' AS role
      FROM users
    WHERE port_control UNION
    SELECT username, 'admin' AS role
      FROM users
    WHERE admin UNION
    SELECT username, 'ldap' AS role
      FROM users
    WHERE ldap UNION
    SELECT username, 'radius' AS role
      FROM users
    WHERE radius UNION
    SELECT username, 'tacacs' AS role
      FROM users
    WHERE tacacs UNION
    SELECT username, 'api' AS role
      FROM users
    WHERE token IS NOT NULL AND token_from IS NOT NULL AND token_from > ( EXTRACT( EPOCH
              FROM now(  ) ) - '3600' )
   ) me
WHERE me.username = 'Jacob'
BEGIN WORK
SAVEPOINT savepoint_0
INSERT INTO admin( action, device, device_key, port, status, subaction, userip, username )
  VALUES( ?, ?, ?, ?, ?, ?, ?, ? ) : '__BULK_INSERT__'
RELEASE SAVEPOINT savepoint_0
COMMIT
10.250.185.185 - - [29/Dec/2020:11:39:42 +0200] "POST /admin/discoverall HTTP/1.1" 302 0 "http://10.251.8.170:5000/admin/jobqueue" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note
  FROM users me
WHERE me.username ILIKE 'Jacob'
SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note
  FROM users me
WHERE me.username ILIKE 'Jacob'
SELECT me.role
  FROM (
    SELECT username, 'port_control' AS role
      FROM users
    WHERE port_control UNION
    SELECT username, 'admin' AS role
      FROM users
    WHERE admin UNION
    SELECT username, 'ldap' AS role
      FROM users
    WHERE ldap UNION
    SELECT username, 'radius' AS role
      FROM users
    WHERE radius UNION
    SELECT username, 'tacacs' AS role
      FROM users
    WHERE tacacs UNION
    SELECT username, 'api' AS role
      FROM users
    WHERE token IS NOT NULL AND token_from IS NOT NULL AND token_from > ( EXTRACT( EPOCH
              FROM now(  ) ) - '3600' )
   ) me
WHERE me.username = 'Jacob'
10.250.185.185 - - [29/Dec/2020:11:39:42 +0200] "GET /admin/jobqueue HTTP/1.1" 200 22922 "http://10.251.8.170:5000/admin/jobqueue" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note
  FROM users me
WHERE me.username ILIKE 'Jacob'
SELECT me.username, me.password, me.token, me.token_from, me.creation, me.last_on, me.port_control, me.ldap, me.radius, me.tacacs, me.admin, me.fullname, me.note
  FROM users me
WHERE me.username ILIKE 'Jacob'
SELECT me.role
  FROM (
    SELECT username, 'port_control' AS role
      FROM users
    WHERE port_control UNION
    SELECT username, 'admin' AS role
      FROM users
    WHERE admin UNION
    SELECT username, 'ldap' AS role
      FROM users
    WHERE ldap UNION
    SELECT username, 'radius' AS role
      FROM users
    WHERE radius UNION
    SELECT username, 'tacacs' AS role
      FROM users
    WHERE tacacs UNION
    SELECT username, 'api' AS role
      FROM users
    WHERE token IS NOT NULL AND token_from IS NOT NULL AND token_from > ( EXTRACT( EPOCH
              FROM now(  ) ) - '3600' )
   ) me
WHERE me.username = 'Jacob'
Odd number of elements in anonymous hash at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 287.
SELECT me.job, me.entered, me.started, me.finished, me.device, me.port, me.action, me.subaction, me.status, me.username, me.userip, me.log, me.debug, me.device_key, to_char( entered, 'YYYY-MM-DD HH24:MI' ), to_char( finished, 'YYYY-MM-DD HH24:MI' ), to_char( started, 'YYYY-MM-DD HH24:MI' ), target.ip, target.creation, target.dns, target.description, target.uptime, target.contact, target.name, target.location, target.layers, target.num_ports, target.mac, target.serial, target.model, target.ps1_type, target.ps2_type, target.ps1_status, target.ps2_status, target.fan, target.slots, target.vendor, target.os, target.os_ver, target.log, target.snmp_ver, target.snmp_comm, target.snmp_class, target.snmp_engineid, target.vtp_domain, target.last_discover, target.last_macsuck, target.last_arpnip
  FROM admin me
  LEFT JOIN device target
    ON target.ip = me.device
WHERE ARRAY( 0x5d9cf28 ) IS NULL AND HASH( 0x666ca60 ) = '-or'
ORDER BY entered DESC, device DESC, action DESC
  LIMIT '50'
[2958] 2020-12-29 09:39:42 error request to GET /ajax/content/admin/jobqueue crashed: DBI Exception: DBD::Pg::st execute failed: ERROR:  syntax error at or near "0"
LINE 1: ...e target ON target.ip = me.device WHERE ( ( ARRAY(0x5d9cf28)...
                                                             ^ [for Statement "SELECT me.job, me.entered, me.started, me.finished, me.device, me.port, me.action, me.subaction, me.status, me.username, me.userip, me.log, me.debug, me.device_key, to_char(entered, 'YYYY-MM-DD HH24:MI'), to_char(finished, 'YYYY-MM-DD HH24:MI'), to_char(started, 'YYYY-MM-DD HH24:MI'), target.ip, target.creation, target.dns, target.description, target.uptime, target.contact, target.name, target.location, target.layers, target.num_ports, target.mac, target.serial, target.model, target.ps1_type, target.ps2_type, target.ps1_status, target.ps2_status, target.fan, target.slots, target.vendor, target.os, target.os_ver, target.log, target.snmp_ver, target.snmp_comm, target.snmp_class, target.snmp_engineid, target.vtp_domain, target.last_discover, target.last_macsuck, target.last_arpnip FROM admin me LEFT JOIN device target ON target.ip = me.device WHERE ( ( ARRAY(0x5d9cf28) IS NULL AND HASH(0x666ca60) = ? ) ) ORDER BY entered DESC, device DESC, action DESC LIMIT ?" with ParamValues: 1='-or', 2='50'] at /home/netdisco/perl5/lib/perl5/DBIx/Class/Schema.pm line 1118.
        DBIx::Class::Schema::throw_exception('DBIx::Class::Version=HASH(0x56e4f78)', 'DBI Exception: DBD::Pg::st execute failed: ERROR:  syntax err...') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage.pm line 112
        DBIx::Class::Storage::throw_exception('DBIx::Class::Storage::DBI::Pg=HASH(0x56e4e10)', 'DBI Exception: DBD::Pg::st execute failed: ERROR:  syntax err...') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1622
        DBIx::Class::Storage::DBI::__ANON__('DBD::Pg::st execute failed: ERROR:  syntax error at or near "...', 'DBI::st=HASH(0x666ed20)', undef) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1958
        DBIx::Class::Storage::DBI::_dbh_execute('DBIx::Class::Storage::DBI::Pg=HASH(0x49a4f60)', 'DBI::db=HASH(0x593e218)', 'SELECT me.job, me.entered, me.started, me.finished, me.device...', 'ARRAY(0x666fb00)', 'ARRAY(0x650b370)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 855
        DBIx::Class::Storage::DBI::__ANON__() called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 130
        DBIx::Class::Storage::BlockRunner::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 71
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x5da1758)', 'Try::Tiny::Catch=REF(0x68f7b00)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 134
        DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/netdisco/perl5/lib/perl5/Context/Preserve.pm line 33
        Context::Preserve::preserve_context('CODE(0x6514b48)', 'replace', 'CODE(0x6671630)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 213
        DBIx::Class::Storage::BlockRunner::_run('DBIx::Class::Storage::BlockRunner=HASH(0x5dbee80)', 'CODE(0x68fcdf0)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/BlockRunner.pm line 105
        DBIx::Class::Storage::BlockRunner::run('DBIx::Class::Storage::BlockRunner=HASH(0x5dbee80)', 'CODE(0x68fcdf0)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 856
        DBIx::Class::Storage::DBI::dbh_do(undef, undef, 'SELECT me.job, me.entered, me.started, me.finished, me.device...', 'ARRAY(0x666fb00)', 'ARRAY(0x650b370)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1939
        DBIx::Class::Storage::DBI::_execute('DBIx::Class::Storage::DBI::Pg=HASH(0x49a4f60)', 'select', 'ARRAY(0x6504b40)', 'ARRAY(0x69202b0)', 'HASH(0x6680b78)', 'HASH(0x6686c70)', 50) called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 2584
        DBIx::Class::Storage::DBI::_select('DBIx::Class::Storage::DBI::Pg=HASH(0x49a4f60)', 'ARRAY(0x68d9e38)', 'ARRAY(0x69202b0)', 'HASH(0x6680b78)', 'HASH(0x651e440)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI/Cursor.pm line 179
        DBIx::Class::Storage::DBI::Cursor::all('DBIx::Class::Storage::DBI::Cursor=HASH(0x6920268)') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/ResultSet.pm line 1294
        DBIx::Class::ResultSet::_construct_results('App::Netdisco::DB::ResultSet::Admin=HASH(0x6901bd8)', 'fetch_all') called at /home/netdisco/perl5/lib/perl5/DBIx/Class/ResultSet.pm line 1821
        DBIx::Class::ResultSet::all('App::Netdisco::DB::ResultSet::Admin=HASH(0x6901bd8)') called at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 287
        App::Netdisco::JobQueue::PostgreSQL::jq_log() called at /home/netdisco/perl5/lib/perl5/App/Netdisco/Web/Plugin/AdminTask/JobQueue.pm line 27
        App::Netdisco::Web::Plugin::AdminTask::JobQueue::__ANON__() called at /home/netdisco/perl5/lib/perl5/Dancer/Plugin/Auth/Extensible.pm line 324
        Dancer::Plugin::Auth::Extensible::__ANON__() called at /home/netdisco/perl5/lib/perl5/Dancer/Plugin/Ajax.pm line 36
        Dancer::Plugin::Ajax::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 71
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x6667c20)', 'Try::Tiny::Catch=REF(0x5da3070)') called at /home/netdisco/perl5/lib/perl5/Dancer/Plugin/Ajax.pm line 41
        Dancer::Plugin::Ajax::__ANON__() called at /home/netdisco/perl5/lib/perl5/Dancer/Route.pm line 274
        Dancer::Route::execute('Dancer::Route=HASH(0x4713788)') called at /home/netdisco/perl5/lib/perl5/Dancer/Route.pm line 189
        Dancer::Route::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 71
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x666a920)', 'Try::Tiny::Catch=REF(0x666ac68)') called at /home/netdisco/perl5/lib/perl5/Dancer/Route.pm line 203
        Dancer::Route::run('Dancer::Route=HASH(0x4713788)', 'Dancer::Request=HASH(0x68fa4c8)') called at /home/netdisco/perl5/lib/perl5/Dancer/Renderer.pm line 137
        Dancer::Renderer::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 76
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x666d048)', 'Try::Tiny::Catch=REF(0x666aab8)') called at /home/netdisco/perl5/lib/perl5/Dancer/Renderer.pm line 146
        Dancer::Renderer::get_action_response('Dancer::Renderer') called at /home/netdisco/perl5/lib/perl5/Dancer/Renderer.pm line 33
        Dancer::Renderer::render_action('Dancer::Renderer') called at /home/netdisco/perl5/lib/perl5/Dancer/Handler.pm line 84
        Dancer::Handler::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 71
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x27cf788)', 'Try::Tiny::Catch=REF(0x667d710)') called at /home/netdisco/perl5/lib/perl5/Dancer/Handler.pm line 113
        Dancer::Handler::render_request('Dancer::Request=HASH(0x68fa4c8)') called at /home/netdisco/perl5/lib/perl5/Dancer/Handler.pm line 76
        Dancer::Handler::handle_request('Dancer::Handler::PSGI=HASH(0x1eea060)', 'Dancer::Request=HASH(0x68fa4c8)') called at /home/netdisco/perl5/lib/perl5/Dancer/Handler.pm line 123
        Dancer::Handler::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/Static.pm line 18
        Plack::Middleware::Static::call('Plack::Middleware::Static=HASH(0x5d90340)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/Expires.pm line 73
        Plack::Middleware::Expires::call('Plack::Middleware::Expires=HASH(0x5d904c0)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/ReverseProxy.pm line 68
        Plack::Middleware::ReverseProxy::call('Plack::Middleware::ReverseProxy=HASH(0x5d90580)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/App/URLMap.pm line 71
        Plack::App::URLMap::call('Plack::App::URLMap=HASH(0x5c037f8)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/Lint.pm line 24
        Plack::Middleware::Lint::call('Plack::Middleware::Lint=HASH(0x1f25e28)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/StackTrace.pm line 38
        Plack::Middleware::StackTrace::__ANON__() called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 71
        eval {...} called at /usr/share/perl5/vendor_perl/Try/Tiny.pm line 67
        Try::Tiny::try('CODE(0x5da1ad0)', 'Try::Tiny::Catch=REF(0x6762320)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/StackTrace.pm line 42
        Plack::Middleware::StackTrace::call('Plack::Middleware::StackTrace=HASH(0x1f259d8)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/AccessLog.pm line 27
        Plack::Middleware::AccessLog::call('Plack::Middleware::AccessLog=HASH(0x5c038b8)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Middleware/ContentLength.pm line 10
        Plack::Middleware::ContentLength::call('Plack::Middleware::ContentLength=HASH(0x5bef960)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Component.pm line 50
        Plack::Component::__ANON__('HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/Plack/Util.pm line 145
        eval {...} called at /home/netdisco/perl5/lib/perl5/Plack/Util.pm line 145
        Plack::Util::run_app('CODE(0x5d956a8)', 'HASH(0x5da36b8)') called at /home/netdisco/perl5/lib/perl5/HTTP/Server/PSGI.pm line 182
        HTTP::Server::PSGI::handle_connection('HTTP::Server::PSGI=HASH(0x5d95510)', 'HASH(0x5da36b8)', 'IO::Socket::INET=GLOB(0x68d7c08)', 'CODE(0x5d956a8)') called at /home/netdisco/perl5/lib/perl5/HTTP/Server/PSGI.pm line 141
        HTTP::Server::PSGI::accept_loop('HTTP::Server::PSGI=HASH(0x5d95510)', 'CODE(0x5bef3f0)') called at /home/netdisco/perl5/lib/perl5/HTTP/Server/PSGI.pm line 63
        HTTP::Server::PSGI::run('HTTP::Server::PSGI=HASH(0x5d95510)', 'CODE(0x5bef3f0)') called at /home/netdisco/perl5/lib/perl5/Plack/Handler/HTTP/Server/PSGI.pm line 14
        Plack::Handler::HTTP::Server::PSGI::run('Plack::Handler::Standalone=HASH(0x1b67698)', 'CODE(0x5bef3f0)') called at /home/netdisco/perl5/lib/perl5/Plack/Loader/Restarter.pm line 31
        Plack::Loader::Restarter::_fork_and_start('Plack::Loader::Restarter=HASH(0x1af97f0)', 'Plack::Handler::Standalone=HASH(0x1b67698)') called at /home/netdisco/perl5/lib/perl5/Plack/Loader/Restarter.pm line 61
        Plack::Loader::Restarter::run('Plack::Loader::Restarter=HASH(0x1af97f0)', 'Plack::Handler::Standalone=HASH(0x1b67698)') called at /home/netdisco/perl5/lib/perl5/Plack/Runner.pm line 279
        Plack::Runner::run('Plack::Runner=HASH(0x18ae1e8)') called at /home/netdisco/perl5/bin/plackup line 10
10.250.185.185 - - [29/Dec/2020:11:39:42 +0200] "GET /ajax/content/admin/jobqueue? HTTP/1.1" 500 510 "http://10.251.8.170:5000/admin/jobqueue" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"

**Comment by ollyg** [comment] 2020-12-29 13:07
Thanks @lupin3rd and @jacobghattas I have located the issue and fixed in
[master b8a63d9a] #758 fix for job queue search

New release to CPAN later today.

**Closed by ollyg** 2020-12-29 13:07 UTC
