### ISSUE TITLE
Issues with IP Reports

### ISSUE THREAD

**Issue by dridge93** [netdisco/netdisco#765] opened 2021-02-04 16:19 UTC
## Expected Behavior

reports/ip/ip inventory page would return the appropriate information

## Current Behavior

reports/ip/ip inventory page don't always return information

## Steps to Reproduce (for bugs)

1. Go to IP Reports page
2. Nothing loads
3. Reload page
4. Sometimes things load

## Context

Affects our customers from being able to consistently access reports for their work
Here are some videos that also display the intermittent issues:

https://user-images.githubusercontent.com/73659781/112031230-7941ea80-8b11-11eb-808a-eedde723755e.mp4

https://user-images.githubusercontent.com/73659781/112031231-7941ea80-8b11-11eb-8a63-fb43ea92905a.mp4

## Your Environment

* Netdisco version used: 2.46.6
* SNMP::Info version used: 3.70

## Device information

`netdisco-do show -d 1.1.1.1 -e specify -DI`

**Comment by inphobia** [comment] 2021-06-10 01:11
interesting...

i haven't yet been able to reproduce this issue, but could it be this issue manifest around the same time arpnip, macsuck or discover is running? default timings for those are:
```
schedule:
  discoverall:
    when: '5 7 * * *'
  macwalk:
    when:
      min: 20
  arpwalk:
    when:
      min: 50
```

while i'm not 100% sure i think we drop old data, then fetch, then insert new data. so there is a small time period the database might not yet contain the relevant info. i'm quite positive this is the case for discover at least.

another possible route is that the database is overloaded. i noticed in the first video that for a /23 it returned almost 1300 records. how big (records & diskspace) are your node & node_ip tables?

finally i'm interested if you are using the default settings for the following or if you changed them. for our medium sized network i'm using:
```
node_freshness: 1500
expire_jobs: 5
#expire_nodes: 3
expire_nodes_archive: 75
```
to keep our node & node_ip tables in check.

**Comment by rc9000** [comment] 2021-09-07 23:08
Hi! I was also not able to reproduce the first issue in the second video. I ran what the page is doing in a loop a couple hundred times, it returned the expected the content every single time - the query matches about 8000 entries in our DB

   for x in $(seq 1 300) ; do curl 'https://netdisco.megacorp.example.org/netdisco/ajax/content/report/ipinventory?subnet=10.170.0.0%2F16&daterange=1970-01-01+to+2021-09-08&limit=8192' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' 2>&1 | tee out$x.txt ; done

But of course it could also be the JS somehow crashing when it reads this Ajax response.

Since this pretty old already, maybe you can give us a ping if you're still experiencing this in the latest version?

**Comment by ollyg** [comment] 2021-10-04 17:03
suspected duplicate of #761

**Closed by ollyg** 2021-10-04 17:03 UTC
