### ISSUE TITLE
Operator calls in update must be in the form

### ISSUE THREAD

**Issue by ciscolive** [netdisco/netdisco#1021] opened 2023-04-06 05:37 UTC
Seems a bug 
```perl
Use of uninitialized value $op in pattern match (m//) at /home/netdisco/perl5/lib/perl5/SQL/Abstract/Classic.pm line 327.
[2930399] 2023-04-06 04:34:27 error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 278
'}, 'DBIx::Class::Exception' )
Use of uninitialized value $op in pattern match (m//) at /home/netdisco/perl5/lib/perl5/SQL/Abstract/Classic.pm line 327.
[2933452] 2023-04-06 04:36:04 error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 278
'}, 'DBIx::Class::Exception' )
Use of uninitialized value $op in pattern match (m//) at /home/netdisco/perl5/lib/perl5/SQL/Abstract/Classic.pm line 327.
[2979150] 2023-04-06 05:31:09 error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 278
'}, 'DBIx::Class::Exception' )
Use of uninitialized value $op in pattern match (m//) at /home/netdisco/perl5/lib/perl5/SQL/Abstract/Classic.pm line 327.
[2979224] 2023-04-06 05:31:29 error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 278
'}, 'DBIx::Class::Exception' )
Use of uninitialized value $op in pattern match (m//) at /home/netdisco/perl5/lib/perl5/SQL/Abstract/Classic.pm line 327.
[2979305] 2023-04-06 05:31:51 error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 278
'}, 'DBIx::Class::Exception' )
Use of uninitialized value $op in pattern match (m//) at /home/netdisco/perl5/lib/perl5/SQL/Abstract/Classic.pm line 327.
[2979361] 2023-04-06 05:32:05 error bless( {'msg' => 'DBIx::Class::SQLMaker::ClassicExtensions::puke(): Fatal: Operator calls in update must be in the form { -op => $arg } at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 278
'}, 'DBIx::Class::Exception' )
```

**Comment by ollyg** [comment] 2023-04-06 08:37
Thanks @ciscolive

I'm going to close this as a duplicate of #993 and unfortunately so far I've not been able to work out why this error is thrown. If you have the opportunity to reproduce it reliably, you can run the following to show the SQL and share it on the other issue? Also can you let me know if you're using the ACI plugin?

`DBIC_TRACE=1 ND2_SINGLE_WORKER=1 bin/netdisco-backend-fg`

Many thanks

**Closed by ollyg** 2023-04-06 08:37 UTC
Labels: assigned-to-project
