### ISSUE TITLE
add web server port config option

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#509] opened 2019-02-15 16:52 UTC
sometimes netdisco-web does not restart when changes are made to deployment.yml, netdisco-backend always seems to restart as expected. as such changes are not always picked up.

## Expected Behavior

some changes require a restart of both -backend & -web, but -web sometimes doesn't restart when deployment.yml is changed.

## Current Behavior

some changes are not processed until a manual restart of netdisco-web.

## Possible Solution

always restart -web when -backend restarts.

## Steps to Reproduce (for bugs)

1. add items to deployment.yml that are in config.yml but not yet in deployment.yml. for example add:
```
table_pagesize: 25
table_showrecordsmenu:
  - [25, 50, 100, 250, '-1']
  - [25, 50, 100, 250, 'All']
```
2. notice that -backend restarts but -web does not.
3. cleaning cookies, browser cache, restarting browser all do not help.
4. after -web restart new values are accepted, and it also seems further changes to the added items restart -web as expected.

## Your Environment

* Netdisco version used: 2.40.3
* SNMP::Info version used: HEAD

**Comment by ollyg** [comment] 2019-02-20 07:36
Hi, can you confirm this isn't another instance of #472 ?

**Comment by inphobia** [comment] 2019-02-20 14:12
i don't think so. i've tested this on both my test setup which uses --port= like #472 but also on our production setup which does not pass any parameters to netdisco-web, so i don't think they're related.

once a key is known in deployment.yml the restart seems to happen, but when adding a key that's known in config.yml to deployment.yml no restart of netdisco-web seems to occur.

**Comment by inphobia** [comment] 2019-02-25 19:06
i need to do some further testing but i noticed that the netdisco-web filewatcher doesn't report changes to deployment.yml in some cases, and as such might not trigger a restart. this led me down a rabid hole on how the filesystem watcher works.
will do some more indepth tracing as soon as time permits.

**Comment by ollyg** [comment] 2019-06-12 10:53
closing due to lack of progress, can reopen or will appear in search if anyone needs it

**Comment by inphobia** [comment] 2019-06-12 11:10
it seems the -web children forget most of their argv data upon restart. not a high prio for me atm, would be handy if web port could be a config option however.

**Comment by ollyg** [comment] 2020-02-13 14:26
I can't reproduce this, the --port option is remembered when netdisco-web self-HUPs (and is coded to do that), sorry

**Closed by ollyg** 2020-02-13 14:26 UTC
Labels: wishlist
