### ISSUE TITLE
App::Netdisco::SSHCollector::Platform::PaloAlto broken ?

### ISSUE THREAD

**Issue by zoeloe** [netdisco/netdisco#755] opened 2020-10-29 23:19 UTC
Well, yes and no, I'm having a problem with the arpnip not showing in the devices webgui.

## Expected Behavior
arp entries fetched with ssh visiable in webgui.

## Current Behavior
web gui doesn't show arpnipped arp entries

## Steps to Reproduce (for bugs)
After I fetched (It seems successfully) the PaloAlto ARP entries:
with:  bin/netdisco-do arpnip -d gjfw1 -DI

SNMP::Info::_global uptime : DISMAN-EVENT-MIB::sysUpTimeInstance : .1.3.6.1.2.1.1.3.0
SNMP::Info::_global description : SNMPv2-MIB::sysDescr.0 : .1.3.6.1.2.1.1.1.0
SNMP::Info::_global id : SNMPv2-MIB::sysObjectID.0 : .1.3.6.1.2.1.1.2.0
SNMP::Info 3.70
SNMP::Info::device_type() layers:01001100 id:25461 sysDescr:"Palo Alto Networks PA-5200 series firewall"
SNMP::Info::_load_attr old_ip_netmask : IP-MIB::ipAdEntNetMask : .1.3.6.1.2.1.4.20.1.3
SNMP::Info::_load_attr new_ip_prefix : IP-MIB::ipAddressPrefix : .1.3.6.1.2.1.4.34.1.5
SNMP::Info::_load_attr new_ip_type : IP-MIB::ipAddressType : .1.3.6.1.2.1.4.34.1.4

[8497] 2020-10-29 20:18:16  info App::Netdisco version 2.046005 loaded.
[8497] 2020-10-29 20:18:16  info arpnip: [172.19.2.100] started at Thu Oct 29 21:18:16 2020
[8497] 2020-10-29 20:18:16 debug arpnip: running with timeout 600s
[8497] 2020-10-29 20:18:16 debug => running workers for phase: check
[8497] 2020-10-29 20:18:16 debug -> run worker check/_base_/0
[8497] 2020-10-29 20:18:16 debug arpnip is able to run
[8497] 2020-10-29 20:18:16 debug => running workers for phase: main
[8497] 2020-10-29 20:18:16 debug -> run worker main/nodes/200
[8497] 2020-10-29 20:18:16 debug cli session cache warm: [172.19.2.100]
[8497] 2020-10-29 20:18:18 debug 172.19.2.100 8497 arpnip()
[8497] 2020-10-29 20:18:20 debug  [172.19.2.100] check_mac - VRRP mac [00:00:5e:00:01:0a] - skipping
[8497] 2020-10-29 20:18:20 debug  resolving 3357 ARP entries with max 50 outstanding requests
[8497] 2020-10-29 20:18:22 debug -> run worker main/nodes/100
[8497] 2020-10-29 20:18:22 debug skip: namespace passed at higher priority
[8497] 2020-10-29 20:18:22 debug -> run worker main/subnets/100
[8497] 2020-10-29 20:18:22 debug snmp reader cache warm: [172.19.2.100]
[8497] 2020-10-29 20:18:22 debug [172.19.2.100:161] try_connect with ver: 2, class: SNMP::Info::Layer3::PaloAlto, comm: <hidden>
[8497] 2020-10-29 20:18:23 debug  [172.19.2.100] arpnip - processed 0 Subnet entries
[8497] 2020-10-29 20:18:23 debug => running workers for phase: store
[8497] 2020-10-29 20:18:23 debug -> run worker store/nodes/0
[8497] 2020-10-29 20:18:34 debug  [172.19.2.100] arpnip - processed 3357 ARP Cache entries
[8497] 2020-10-29 20:18:34 debug  [172.19.2.100] arpnip - processed 0 IPv6 Neighbor Cache entries
[8497] 2020-10-29 20:18:34  info arpnip: finished at Thu Oct 29 21:18:34 2020
[8497] 2020-10-29 20:18:34  info arpnip: status done: Gathered arp caches from 172.19.2.100

The webgui is empty: see https://gist.github.com/zoeloe/8a325cf31ecfdde0450390b4455fc7e8

## Your Environment

Software	Version
App::Netdisco	2.46.5
SNMP::Info	3.70
DB Schema	63
PostgreSQL	9.5.14
Perl	5.22.1

## Config info (deployment.yml)
sensitive: what I can say is that the credentials are correct for the ssh connection and the device_auth with the device in the dumpconfig seems correct.

## Device information
Palo Alto specific problem

**Comment by rc9000** [comment] 2020-10-29 23:57
Hi @zoeloe 

From the output it looks like the arpnip goes ok:

    debug [172.19.2.100] arpnip - processed 3357 ARP Cache entries

But  arpnip fills the node_ip table in the database (arp table ip:mac pairs), and your CSV shows the Neighbor IP/DNS columns empty which on the other hand are filled by LLDP/CDP/etc. discovery and stored in device_port. Is the IP / neighbor you expect to see another SNMP-capable device that Netdisco should discover, or just some random client? Depending on that you'd need to look into either into the discovery of the remote_(ip|port|type|id) attributes or the node_ip -> node -> device_port chain.

**Comment by zoeloe** [comment] 2020-10-30 00:22
I know the CSV is a bit confusing. One would expect the arp entries fetched by the ssh gather script in the webgui.
I'll illustrate with a picture.

<img width="1414" alt="Screen Shot 2020-10-30 at 01 15 43" src="https://user-images.githubusercontent.com/34719795/97645602-ac45ed80-1a4d-11eb-9a1d-f2101148c642.png">

So, no I'm not expecting neigbours, but nodes.
The arpnip ssh script should do that, doesn't it !
I don't think the Palo Alto devices has knowledge about LLDP/CDP/etc.. neigbours anyway. either through SNMP or ssh arpnip.

Thanks for your comment.

**Comment by inphobia** [comment] 2020-10-30 06:24
i could be way of here, but arpnip, either via snmp or ssh, provides a mapping between ip<->mac for nodes.

iirc it's macsuck that provides the interface<->mac mappings.

(node table for the mac->port/vlan/device mapping & node_ip table for the mac<->ip mapping)

if reports->ip->subnet usage has info arpnip should work.

**Comment by rc9000** [comment] 2020-10-30 23:48
Yes l agree with @inphobia, since your screenshot does not show any mac addresses in the "connected nodes" column, the issue seems to be the node port -> mac mappings not working. The mac -> ip mappings are just sugar on top of it.


I don't have access to any PaloAlto gear, but maybe we can see where it goes wrong if you can post a `netdisco-do -DISQ -d <ip> macsuck` output?

**Comment by zoeloe** [comment] 2020-10-31 01:40
Hi @rc9000,
Thanks for the input.  Isn't the purpose of the App::Netdisco::SSHCollector::Platform::PaloAlto module to get the ARP pairs ?
The ssh module says "Collect ARP entries from PaloAlto devices."
As you can see below. The device isn't "macsuckable" as such. 

[27042] 2020-10-31 01:18:09  info App::Netdisco version 2.046005 loaded.
SELECT me.version, me.installed 
  FROM dbix_class_schema_versions me 
WHERE 1 = 0
SELECT me.version 
  FROM dbix_class_schema_versions me 
ORDER BY installed DESC 
  LIMIT '1'
SELECT me.ip, me.alias, me.subnet, me.port, me.dns, me.creation 
  FROM device_ip me 
WHERE me.alias = '172.19.2.100' AND me.ip = '172.19.2.100'
SELECT me.ip, me.creation, me.dns, me.description, me.uptime, me.contact, me.name, me.location, me.layers, me.num_ports, me.mac, me.serial, me.model, me.ps1_type, me.ps2_type, me.ps1_status, me.ps2_status, me.fan, me.slots, me.vendor, me.os, me.os_ver, me.log, me.snmp_ver, me.snmp_comm, me.snmp_class, me.snmp_engineid, me.vtp_domain, me.last_discover, me.last_macsuck, me.last_arpnip, to_char( me.creation, 'YYYY-MM-DD HH24:MI' ), to_char( me.last_arpnip, 'YYYY-MM-DD HH24:MI' ), to_char( me.last_discover, 'YYYY-MM-DD HH24:MI' ), to_char( me.last_macsuck, 'YYYY-MM-DD HH24:MI' ), extract( epoch 
      FROM age( now(  ), me.creation ) ), extract( epoch 
      FROM age( now(  ), me.last_arpnip ) ), extract( epoch 
      FROM age( now(  ), me.last_discover ) ), extract( epoch 
      FROM age( now(  ), me.last_macsuck ) ), replace( age( timestamp 'epoch' + me.uptime / 100 * interval '1 second', timestamp '1970-01-01 00:00:00-00' ) ::text, 'mon', 'month' ) 
  FROM device me 
WHERE me.ip = '172.19.2.100'
[27042] 2020-10-31 01:18:09  info macsuck: [172.19.2.100] started at Sat Oct 31 02:18:09 2020
[27042] 2020-10-31 01:18:09 debug macsuck: running with timeout 600s
[27042] 2020-10-31 01:18:09 debug => running workers for phase: check
[27042] 2020-10-31 01:18:09 debug -> run worker check/_base_/0
[27042] 2020-10-31 01:18:09 debug is_macsuckable: 172.19.2.100 has no layer 2 capability
[27042] 2020-10-31 01:18:09 debug macsuck skipped: 172.19.2.100 is not macsuckable
[27042] 2020-10-31 01:18:09  info macsuck: finished at Sat Oct 31 02:18:09 2020
[27042] 2020-10-31 01:18:09  info macsuck: status info: macsuck skipped: 172.19.2.100 is not macsuckable


To be complete, I've done the arpnip of the device in the gist below:
https://gist.github.com/zoeloe/0cab0fdf56435bfac8aca2ed5505fb9b
Which seems to be working IMHO.

Thanks for your time and ideas.

**Comment by ollyg** [comment] 2020-10-31 10:38
Hi @zoeloe so indeed the problem is that Netdisco thinks the device cannot give MAC<->port mappings (macsuck).

To be clear, arpnip is the ARP table which is IP<->MAC. So you just have this bunch of IPs and MAC addresses in Netdisco but it doesn't know which ports to put them on without the macsuck. The SSH retrieval is only ARP, I'm afraid.

One solution may be to change the "layers" reported by your device ("has no layer 2 capability" in the log). For example here in the docs is how to set that for a Linux server (and anything based on it such as soft routers): https://github.com/netdisco/netdisco/wiki/Vendor-Tips#linux-snmp-service-agent

**Comment by ollyg** [comment] 2020-10-31 10:39
As the PaloAlto SSH collector is not broken, I'll close this ticket. We could have a new ticket in SNMP::Info repo if we need to fix the device class for this platform (to be clear, not a lot Netdisco can do about it).

**Closed by ollyg** 2020-10-31 10:39 UTC

**Comment by mdeng10** [comment] 2022-07-06 00:51
> Hi @zoeloe so indeed the problem is that Netdisco thinks the device cannot give MAC<->port mappings (macsuck).
> 
> To be clear, arpnip is the ARP table which is IP<->MAC. So you just have this bunch of IPs and MAC addresses in Netdisco but it doesn't know which ports to put them on without the macsuck. The SSH retrieval is only ARP, I'm afraid.
> 
> One solution may be to change the "layers" reported by your device ("has no layer 2 capability" in the log). For example here in the docs is how to set that for a Linux server (and anything based on it such as soft routers): https://github.com/netdisco/netdisco/wiki/Vendor-Tips#linux-snmp-service-agent

Hi @ollyg, i'm experiencing the same problem here but unfortuntaely i don't think there's a way to modify the layers reported on a palo alto device. I've tried modifying the bits directly in the database for it to be seen as an L2 device and also doing a macsuck via `netdisco-do discover ...` but that wasn't able to get the MAC -> Port mapping either. 

The MAC -> Port mapping is definitely retrievable either by SNMP or SSH + CLI commands or even via API, what steps would need to be taken to support this? I'm happy to attempt writing this myself if you could point me in the right direction

**Comment by rc9000** [comment] 2022-07-20 09:37
@mdeng10 to do a macsuck with netdisco-do, you'd need to 

 * run `netidsco-do discover` so netdisco learns the device
 * best stop netdisco-backend so it will not interfere with the next step
 * edit the layers in the db like you did
 * do not run discover again, as it will overwrite the layers
 * instead, run `netdisco-do macsuck`

Maybe like this you get anything?

If not, the way to get a non-SNMP macsuck into Netdisco are:

 * implement something like the arpnip SSHCollector but for macsuck, there is a lot of good info in 
    * https://github.com/netdisco/netdisco/wiki/Developing
    * https://github.com/netdisco/netdisco/wiki/Backend-Plugins
    * [the main commit of the whole SSH arpnip feature](https://github.com/netdisco/netdisco/commit/d44a8f56ea25496d460fb7708dd5436dd61abcb8)

Alternatively, we have an API in the meantime, so maybe adding and endpoint to submit a generic macsuck result would be great.

If you're interested in implementing something, maybe open this as a new discussion in the repo and we can talk about more details.

**Comment by mdeng10** [comment] 2022-07-21 00:46
appreciate the reply @rc9000 

> - run netidsco-do discover so netdisco learns the device
> - best stop netdisco-backend so it will not interfere with the next step
> - edit the layers in the db like you did
> - do not run discover again, as it will overwrite the layers
> - instead, run netdisco-do macsuck

this wasn't able to discover any MAC addresses unfortunately - perhaps an API endpoint to submit a generic macsuck result would work, as i doubt i'd be able to create the SSH-based macsuck, in any case happy to revisit later down the track

**Comment by ollyg** [comment] 2022-07-21 10:25
We should still patch SNMP::Info::Layer3::PaloAlto so that it returns layer 2. Even an API to inject macsuck data would not work if the device is not layer 2 capable.
