### ISSUE TITLE
Using netdisco-do in crontab generate e-mails every time

### ISSUE THREAD

**Issue by BerndHanisch** [netdisco/netdisco#1100] opened 2023-08-30 10:58 UTC
Using netdisco-do in a cron job generate every time a email message because the tool use stderr for the info messages. a redirect 1> /dev/null cant be used.

## Possible Solution
change output to "stdout" and only use "stderr" for errors

## Steps to Reproduce (for bugs)
~/bin/netdisco-do arpnip -d 192.168.1.1 -p $tmpfile 1> /dev/null
==> output:
[42619] 2023-08-30 10:46:17  info App::Netdisco version 2.060003 loaded.
[42619] 2023-08-30 10:46:17  info arpnip: [192.168.1.1] started at Wed Aug 30 12:46:17 2023
[42619] 2023-08-30 10:46:17  info arpnip: finished at Wed Aug 30 12:46:17 2023
[42619] 2023-08-30 10:46:17  info arpnip: status done: Ended arpnip for 192.168.1.1

## Context
Usage of netdisco-do in cronjob generate every time an email. 

## Your Environment
App::Netdisco version 2.060003

**Comment by ollyg** [comment] 2023-08-31 10:17
Thanks @BerndHanisch this is a very good suggestion

**Comment by ollyg** [comment] 2023-09-02 18:35
Hi @BerndHanisch I realised that this behaviour is already supported by adding the --quiet flag to the command. Please try that and do let me know if that isn't working for you.

**Comment by ollyg** [comment] 2023-09-04 09:35
@BerndHanisch just checking ... --quiet (not --quit) yes? I will look into it...

**Comment by ollyg** [comment] 2023-09-09 07:39
Hi again, closing this as I cannot reproduce the issue, sorry. This is completely silent for me:
```
bin/netdisco-do arpnip -d 127.0.0.1 -p ~/tmp/arps --quiet
```

**Closed by ollyg** 2023-09-09 07:39 UTC
Labels: assigned-to-project
