### ISSUE TITLE
Missing Map Links

### ISSUE THREAD

**Issue by vbep** [netdisco/netdisco#370] opened 2018-02-06 04:13 UTC
Hi all, apologies firstly - I asked this in IRC but am unable to keep the connection open from work so I've lost any answer that was provided.

Expected Behavior
Neighbour map shows links between objects that are shown as "Connected Devices" on the "Ports" tab.

Current Behaviour
I've upgraded to 2.39.1 for the new mapping options. My devices still discover ok and I can see device neighbours listed on the Ports tab. If I go to the Neighbours map for a selected device I have a single object with the text "ERROR: Your data contains an empty nodes array."

If i redraw with All Devices radio button checked then I can see the majority of (not all of) my 50 odd switches. I have 2 pairs of switches displaying links between themselves, but the remainder are not linked. On these 4 devices if I view them in "Neighbours Only" mode they display ok (as they look on the All Devices draw).

I have installed/configured with a completely new DB - same result. I've installed on a clean Debian install and as far as the map goes - same result. 

If anyone had access to the IRC answer (if any) a copy and paste here is most welcome.

Thanks for reading.

Steps to Reproduce (for bugs)
I've seen this with a clean install of Debian 8 using postgres 9.6. Also seen after upgrading an old installation on postgres 9.4

Your Environment
* Netdisco version used: 2.39.1
* SNMP::Info version used: 3.43

**Comment by vbep** [comment] 2018-02-27 02:33
Still no luck on this one. I'm not sure how to proceed, it seems to only be a problem with the map. Neighbor devices exist and show links to each other.

Just updated to 2.39.11 and tried deleting and rediscovering some test devices - same result.

I have taken some screenshots to show what's happening, they're in a google drive shared folder, public link: https://drive.google.com/drive/folders/1KIDDAtdTtDIb-cXSm8U-Cso4Ql3loyTK

Any ideas?

Thanks.

**Comment by ollyg** [comment] 2018-02-27 07:52
Hi @vbep, thanks for the screenshots. Almost certainly this is an issue with our SQL and not your system or installation. Would it be possible to send me the content of your device and device_ports tables?

You can run the following:

    ~netdisco/bin/netdisco-do psql --quiet -e 'COPY (SELECT * FROM device) TO STDOUT WITH CSV HEADER'
    ~netdisco/bin/netdisco-do psql --quiet -e 'COPY (SELECT * FROM device_port) TO STDOUT WITH CSV HEADER'
    ~netdisco/bin/netdisco-do psql --quiet -e 'COPY (SELECT * FROM device_ip) TO STDOUT WITH CSV HEADER'

You can email this to oliver@cpan.org as it will contain information you probably don't want on github. Then I will be able to simulate your setup and see what's going on. I hope that's OK but let me know if not.

Should you feel more adventurous, then the problematic query is _probably_ this one:

    ~netdisco/perl5/lib/perl5/App/Netdisco/DB/Result/Virtual/DeviceLinks.pm

Oliver.

**Comment by vbep** [comment] 2018-02-28 03:43
Emailed @ollyg thanks very much.

**Comment by ollyg** [comment] 2018-02-28 07:59
After looking at the data sent by @vbep (thanks!) I don't think the issue lies in the SQL after all.

The Ubiquiti and Dlink classes used for these devices are not returning clean data (or Netdisco is having a problem with the data) for remote_port, remote_ip, and also the port name/descr fields. This breaks the ability to link devices.

For example looking at the device_ports table, a filter on remote_type for the "Procurve" items shows a clean remote_ip and remote_port field. However a filter on remote_type for "EdgeSwitch" or "DGS" shows that the remote_port has either a MAC address or description - not what we want.

Next step would be to get the output of the following command (again, direct to me is fine) for a set of Dlink and Ubiquiti devices that are connected, to improve the SNMP::Info classes:

    snmpwalk -v 2c -c <community> -ObentU <device> .1

It would be worth making sure the devices in question are running up to date software before doing this, to remove any bugs in their SNMP implementations that are since fixed.

Oliver.

**Comment by LBegnaud** [comment] 2018-02-28 15:48
I know for a fact that older EdgeSwitch firmware had issues with reporting neighbor ips (check the release notes and you'll see bug reports credited to me!). It wouldn't surprise me if they had other issues as well.

Here's an example of LLDP neighbor output on the newest firmware, if that helps. I think they just aren't following standards:

![image](https://user-images.githubusercontent.com/15981748/36796981-7d518c1e-1c6c-11e8-8755-0c5e6192088c.png)

**Comment by Linwood-F** [comment] 2018-03-03 21:40
Not just DLink or Ubiquiti.... Cisco: 

I just did a new installation with a bunch of Cisco devices (two 3650, 14 3560CX) all set up to allow SNMP (and indeed discover worked and it found everything an din a brief look it seemed to discover properly). 

And I'm getting the same error.

This was a new, clean install.  All are connected in a big circle (it's in a provisioning lab at the moment) and all have CDP and LLDP enabled and all see each other if I look manually.  All Cisco's are on the latest version of the IOS/IOSXE software, just downloaded as of last week.   Because all are physically in the same room there's no delays or connectivity issues.  These are physical devices not simulation, brand new.

One 3650 sees one 3560CX.

The other 3650 shows the empty message, as do about half the 3560CX's.  I can see no apparent pattern in which show empty and which do not.  When one has a neighbor, it's neighbor also shows itself as a neighbor (i.e. where neighbors are present they are symmetric and correct). 

A discover all shows no error on the job queue page.  

This is 2.39.13 on Ubuntu 16.04.04, db schema 48, PostgreSQL 9.5.11 Perl 5.22.1 SNMP Info 3.49.

Any thoughts where to go next?

**Comment by Linwood-F** [comment] 2018-03-03 22:24
I took a look at one that showed an empty message, and dumped its CDP MIB, here are some relevant portions.  The hex encoded IP's look right, i.e. not only is it correct externally if I translate and go into netdisco it shows the right device.

CISCO-CDP-MIB::cdpCacheAddress.10106.4 = Hex-STRING: AC 1F 28 01
CISCO-CDP-MIB::cdpCacheAddress.10107.2 = Hex-STRING: AC 1F 19 0A
CISCO-CDP-MIB::cdpCacheAddress.10111.3 = Hex-STRING: AC 10 0B 02
CISCO-CDP-MIB::cdpCacheAddress.10112.1 = Hex-STRING: AC 10 0C 04
CISCO-CDP-MIB::cdpCacheDeviceId.10106.4 = STRING: realname1
CISCO-CDP-MIB::cdpCacheDeviceId.10107.2 = STRING: realname2
CISCO-CDP-MIB::cdpCacheDeviceId.10111.3 = STRING: realname3
CISCO-CDP-MIB::cdpCacheDeviceId.10112.1 = STRING: realname1
CISCO-CDP-MIB::cdpCacheDevicePort.10106.4 = STRING: GigabitEthernet1/0/6
CISCO-CDP-MIB::cdpCacheDevicePort.10107.2 = STRING: GigabitEthernet0/7
CISCO-CDP-MIB::cdpCacheDevicePort.10111.3 = STRING: GigabitEthernet0/12
CISCO-CDP-MIB::cdpCacheDevicePort.10112.1 = STRING: GigabitEthernet0/12
CISCO-CDP-MIB::cdpCachePlatform.10106.4 = STRING: cisco WS-C3650-24TD
CISCO-CDP-MIB::cdpCachePlatform.10107.2 = STRING: cisco WS-C3560CX-12TC-S
CISCO-CDP-MIB::cdpCachePlatform.10111.3 = STRING: cisco WS-C3560CX-12TC-S
CISCO-CDP-MIB::cdpCachePlatform.10112.1 = STRING: cisco WS-C3560CX-12TC-S

**Comment by ollyg** [comment] 2018-03-04 17:29
Hi @Linwood-F many thanks for posting! I saw your IRC note, and while this might be a separate issue, the updated Netmap is new code so I am not ruling out cases it cannot yet handle.

If you scroll up and see the comment here: https://github.com/netdisco/netdisco/issues/370#issuecomment-368777260

Then are you able to run those commands for two devices which show links in Device Ports table but not on the map, and send the output to oliver@cpan.org ? I will delete the files after use.

If you can't do that, then you can also look at the SQL statement posted in that same comment which is the one looking at neighbor ports. I wonder whether it's excluding some ports on your devices.

Oliver

**Comment by ollyg** [comment] 2018-03-05 07:52
Thanks for the files @Linwood-F it's very helpful. I can at first see that the "speed" field in device_ports is not showing *bps but a plain number such as "309000000". Can you help me interpret that?

**Comment by Linwood-F** [comment] 2018-03-05 14:25
The routers when deployed will be linked with microwave in many cases, so the interfaces specify the speed planned for them.  

In the configs they look like this: 

```
interface GigabitEthernet1/0/11
 description Legacy Link to xxxxxxxx
 no switchport
 bandwidth 155000
 ip address xxx.xxx.xxx.xxx 255.255.255.0
end

```
A show interface will yield: 

```
xxxxxxx#show int gi1/0/11
GigabitEthernet1/0/11 is down, line protocol is down (notconnect)
  Hardware is Gigabit Ethernet, address is 4001.7a93.ccd7 (bia 4001.7a93.ccd7)
  Description: Legacy Link to xxxxxxxx
  Internet address is xxx.xxx.xxx.xxx/24
  MTU 1500 bytes, BW 155000 Kbit/sec, DLY 10 usec,
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
```

Which seems to correspond to the prompted import format: 

```
xxxxx(config)#int gi1/0/11
xxxxx(config-if)#band ?
  <1-40000000>  Bandwidth in kilobits
  inherit       Specify how bandwidth is inherited

```

Is it causing an issue?  The routers when deployed will have heavily redundant links, this helps get EIGRP using the fastest of paths in its choices, but if you think it is causing the issue as an experiment I can remove some.

**Comment by ollyg** [comment] 2018-03-05 15:12
Thanks @Linwood-F, I don't propose you change any topology. We probably need to amend the query which generates the topology map. Currently gathering speeds is part of the query so that the map can show aggregate speed between devices. I think this should be relaxed to allow support for your situation.

I'll let you know when we have an updated version to test.

**Comment by Linwood-F** [comment] 2018-03-05 15:20
Interesting, so you think those actually are causing this?  I would think that they all appear all the time but as 1000000.  But sure, this is a great time for me to test something as we are still in a lab environment testing physical hardware.

**Comment by ollyg** [comment] 2018-03-05 15:24
Yes, you can see the SQL query here: https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/DB/Result/Virtual/DeviceLinks.pm

And line 37 filters for rows which report an understandable speed in *bps (actually SNMP::Info library underneath Netdisco is setting this from its knowledge of devices). The query needs updating to remove this restriction but also to amend the speed so it's not then reproduced as an unintelligible number in the netmap (hence me asking about how to interpret 309000000 - but I think we'll just ignore it instead).

**Comment by Linwood-F** [comment] 2018-03-05 15:57
I see the issue, the case statement has an else that probably works, but the join condition doesn't permit the same else.  The case won't handle things like "OC-3" either by the way.

I would argue the issue is that the SNMP utilities are doing a translation themselves to attach a speed (or in the case of some values replace it with a name, e.g. OC-3, that is not a number).   While handy for humans, I wonder if this is not itself rather inappropriate.  The actual MIB returns a simple number (not sure if you are pulling ifspeed or ifhighspeed but both do).  If everything just remained the mib value itself, no units, no conversion, I guess it might work? 

I wonder if the more solid fix is not to stop doing the translation (or maybe just translate to mbs, or to be conservative kbs for everything, not try to guess what media it is?  After all, "OC-3" implies a speed, but it is really a media, and just running at 155mbs doesn't mean I have an OC-3 circuit (in this case it is just a coincidence). 

Regardless, however you fix, I'm happy to test.
```
IF-MIB::ifSpeed.1 = Gauge32: 1000000000
IF-MIB::ifSpeed.2 = Gauge32: 4294967295
IF-MIB::ifSpeed.3 = Gauge32: 1000000000
IF-MIB::ifSpeed.4 = Gauge32: 1000000000
IF-MIB::ifSpeed.5 = Gauge32: 1000000000
IF-MIB::ifSpeed.6 = Gauge32: 1000000000
IF-MIB::ifSpeed.12 = Gauge32: 1000000000
IF-MIB::ifSpeed.13 = Gauge32: 309000000
IF-MIB::ifSpeed.14 = Gauge32: 309000000
etc
IF-MIB::ifHighSpeed.1 = Gauge32: 1000
IF-MIB::ifHighSpeed.2 = Gauge32: 10000
IF-MIB::ifHighSpeed.3 = Gauge32: 1000
IF-MIB::ifHighSpeed.4 = Gauge32: 1000
IF-MIB::ifHighSpeed.5 = Gauge32: 1000
IF-MIB::ifHighSpeed.6 = Gauge32: 1000
IF-MIB::ifHighSpeed.12 = Gauge32: 1000
IF-MIB::ifHighSpeed.13 = Gauge32: 309
IF-MIB::ifHighSpeed.14 = Gauge32: 309
etc
```

**Comment by ollyg** [comment] 2018-03-05 21:44
OK I've written an initial patch for this which will require a rediscover of all devices (or wait a day) in order to recover the raw speed from all ports. Needs testing.

**Comment by Linwood-F** [comment] 2018-03-05 21:49
Happy to do so, how do I get it?  

Do I need to delete them first or just run discover-all?

**Comment by ollyg** [comment] 2018-03-05 21:55
I'm running a test on a network right now. If that seems OK then I'll simply push a new CPAN release for you to install. Will let you know soon... :-)

**Comment by ollyg** [comment] 2018-03-05 23:02
Version 2.039015 on its way to CPAN. You will see it in a couple of hours. Let me know how it goes!

**Comment by ollyg** [comment] 2018-03-05 23:02
(remember to run a discoverall after upgrade - it will work fine without but there will be no link speeds on the netmap until you do)

**Comment by Linwood-F** [comment] 2018-03-06 00:28
It worked perfectly, all the devices are connected exactly as expected.  Thank you!

**Comment by vbep** [comment] 2018-03-06 05:48
I've done a full reinstall of 2.39.15 and map links are still an issue. Neighbours are correctly shown in the port list however - as before. Many thanks for your efforts - I've emailed direct with more info. Cheers.

**Comment by ollyg** [comment] 2018-03-07 20:23
Hi @vbep many thanks for the email and attachments.

The issue in your case is that what Netdisco records for the "port name" of a device port is different to what the device is advertising to its neighbor over LLDP (and what gets recorded in our remote_port column). Hence Netdisco cannot match left and right sides of links.

So this is not an issue with the device map, but an issue with the Ubiquiti device class selecting poor interface names. Please could you email me the output of the following command for a couple of the Ubiquiti devices?

    snmpwalk -v 2c -c <community> -ObentU <device> .1

(If this is not the issue with the Dells, we can look at that after)

Many thanks!

**Comment by vbep** [comment] 2018-03-13 22:12
I've sent through the walks. The thing is this was all linking/mapping fine in the old version before the new map. I am sure you know better than I do what's going on but it indicates to me that the SQL join has changed to something that the Ubiquiti switches are no longer applicable to where previously, in the old netdisco version, they were.

So side question - can't find doc - can i install an old version of netdisco to get my maps back? Some argument I can pass here curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 App::Netdisco
?

Many thanks for your excellent work.

**Comment by ollyg** [comment] 2018-03-17 14:28
Hi @vbep many thanks for the snmpwalks. I've updated the SNMP::Info code for Ubiquiti and tested that the links are made between devices. This will be in the next release of Netdisco (not sure when that will be).

Be aware that Ubiquiti still seems to return junk values for some important fields (such as "Spare" for the neighbor port name). Let us know how you get on, but we might not be able to fix all issues.

**Comment by Linwood-F** [comment] 2018-03-18 19:04
I've now stumbled into the DLink world at a client, and finding some things that I do not quite understand, and wonder if they are addressed in what you were working on.

One issue is that the dlink is reporting its interface type as "gigabitEthernet" instead of "ethernetCsmacd", and the query is hard coded to be "ethernetCsmacd".  Is there a benefit of joining over that?  And/or I guess I could change to an "or".

The other is that the discover for LLDP on the attached Cisco is showing the remote port as:

D-LinkDGS-3120-48PCR1.02.013Port41onUnit1

But the port (not remote_port) field in the device_port  for the dlink ip is 

D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1

The cisco one has been compressed out.  When I do an SNMP query (though I am unsure what OID you use), I get it not compressed out, here's a walk: 

```
netdisco@xxxxx:~/perl5/lib/perl5/App/Netdisco/DB/Result/Virtual$ snmpwalk -v2c -c xxxxxxxx 
 192.168.1.1 1.0.8802.1.1.2.1.4.1.1 | grep -P "\.6\s"
iso.0.8802.1.1.2.1.4.1.1.4.0.18.6 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.5.0.18.6 = Hex-STRING: 84 C9 B2 19 51 68
iso.0.8802.1.1.2.1.4.1.1.6.0.18.6 = INTEGER: 7
iso.0.8802.1.1.2.1.4.1.1.7.0.18.6 = Hex-STRING: 31 2F 34 31 00
iso.0.8802.1.1.2.1.4.1.1.8.0.18.6 = STRING: "D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1"
iso.0.8802.1.1.2.1.4.1.1.9.0.18.6 = STRING: "XXXXXXXXX"
iso.0.8802.1.1.2.1.4.1.1.10.0.18.6 = STRING: "Gigabit Ethernet Switch"
iso.0.8802.1.1.2.1.4.1.1.11.0.18.6 = Hex-STRING: 60 00
iso.0.8802.1.1.2.1.4.1.1.12.0.18.6 = Hex-STRING: 60 00

```

It looks at least on the surface as though something is stripping spaces before it stores the lldp results into the device_port table?   But for remote_port on cisco not port on the dlink?

I've got another issue as well, and am not quite sure what to make of it.  The device_port table shows, for the cisco's ip, a "port" of GigabitEthernet1/0/18, but the dlink's remote_port field is "Gi1/0/18".  When I query the dlink via snmp I get the same: 

```
netdisco@xxxxxx:~/perl5/lib/perl5/App/Netdisco/DB/Result/Virtual$ snmpwalk -v2c -c xxxxxxxx 10.162.0.10  1.0.8802.1.1.2.1.4.1.1 | grep -P "1/0/18"
iso.0.8802.1.1.2.1.4.1.1.7.117961286.41.3 = STRING: "Gi1/0/18"
```

But the SHOW LLDP NEIGHBOR command on the cisco ALSO shows Gi1/0/18, so I think it's the Cisco that is sending that value over: 

```
the_cisco#show lldp neigh det
------------------------------------------------
Local Intf: Gi1/0/18
Chassis id: 84c9.xxxxx.5168
Port id: 1/41
Port Description: D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1
System Name: xxxxx
```

The same cisco switch (3650, current IOS) for show cdp neigh details shows the full interface name as the local interface.  Does this mean that it's a cisco problem with LLDP?   I would certainly think that would have shown up agest ago. 

I can patch the query for all this, though it's a bit ugly, and I have no idea what side effects it may have elsewhere.  I offer it here in case it's interesting to someone or @ollyg may have comments.  The changes are in the last inner join's ON and the first AND in the where.

Also, we have a few ubiquiti's that are next on my list -- is that code you updated isolated in a commit?

```
 SELECT dp.ip AS left_ip, ld.dns AS left_dns, ld.name AS left_name,
        array_agg(dp.port) AS left_port, array_agg(dp.name) AS left_descr,
        sum( COALESCE(dpp.raw_speed,0) ) as aggspeed,
        count(*) AS aggports,
        dp2.ip AS right_ip, rd.dns AS right_dns, rd.name AS right_name,
        array_agg(dp2.port) AS right_port, array_agg(dp2.name) AS right_descr
 FROM device_port dp
 LEFT OUTER JOIN device_port_properties dpp USING (ip, port)
 INNER JOIN device ld ON dp.ip = ld.ip
 INNER JOIN device_ip di ON dp.remote_ip = di.alias
 INNER JOIN device rd ON di.ip = rd.ip
 INNER JOIN device_port dp2 ON (di.ip = dp2.ip AND replace(replace(replace(dp.remote_port,' ',''),'GigabitEthernet',''),'Gi','') = replace(replace(replace(dp2.port,' ',''),'GigabitEthernet',''),'Gi','') )
 WHERE dp.remote_port IS NOT NULL
   AND dp.type in ('gigabitEthernet', 'ethernetCsmacd')
   AND dp.ip <= dp2.ip
 GROUP BY left_ip, left_dns, left_name, right_ip, right_dns, right_name
 ORDER BY dp.ip
```

**Comment by Linwood-F** [comment] 2018-03-18 20:15
Well, I take it back -- the query above works, but I did a discover all (and then all the macsucks, etc.) and it still doesn't show.  It's actually more strange than that, if I go to the DLink switch, neighbors, and "All Devices", that switch is actually not on the map at all, the switch itself is missing from the map, not (just) the link. Zoom to this device does nothing (since it's not there).  Same with any map display I use, something about these links, maybe, is suppressing the display?

**Comment by vbep** [comment] 2018-03-19 01:10
Hey again, I have one D-Link missing from my map as well @Linwood-F. It's the only one that I can see that is missing. It exists in the DB and has connected devices displayed in the table as expected. I'd still like to roll back to the old map version :S

**Comment by ollyg** [comment] 2018-03-19 14:29
Hi @vbep and @Linwood-F many thanks for the additional info. I have updated the query to remove the ethernetCsmacd restriction and will push a new release of Netdisco soon.

I will also note that the reason you are having trouble, and that the results of the map are different to the previous map version, is that port names now MUST match on both sides of a link to allow it to feature in the map. The previous map version was arguably very broken and wrong in its display (I would not advise rolling back). The new version is better, but is exposing results for some platforms (such as D-Link) that should be fixed. We can patch those.

For example "D-Link DGS-3120-48PC R1.02.013 Port 41 on Unit 1" should probably be "1/41" and the Cisco could have better port naming. Please open new tickets against SNMP::Info to fix this, at https://github.com/netdisco/snmp-info/issues/new.

**Closed by ollyg** 2018-03-19 14:29 UTC
Labels: bug

**Comment by Linwood-F** [comment] 2018-03-19 14:37
OK, I can do that, though I think that 1/41 is not really right as what LLDP on the cisco sees is the long string.

Would you be kind enough to comment on link issue?   I forced the query to find a match, but the node disappears.  I.e. if I run the SQL the link I want to see is present, but the left-side node itself disappears from the map. Do you believe that is being caused by the port naming issue, or could it be yet something else? 

I.e. once past the query, what could make the node disappear (not just the link but the node itself even in "all" mode) from the map?

**Comment by Linwood-F** [comment] 2018-03-19 18:38
@ollyg I don't know quite where to put this, but am going to suggest it be re-opened here if you agree this is an issue. 

There is an issue that causes map node (not links) to disappear related to your fix above.

In ~/perl5/lib/perl5/App/Netdisco/DB/Result/Virtual/DevicePortSpeed.pm, there is a similar restriction. Once I removed it, and also forced the port name comparisons as in my SQL above for the neighbor connection, I get my Dlink's connected to my Cisco, and now the Dlink's to Netgear, though the DLink's are not connecting to each other yet, need to look further at that.

I'd suggest that one could be removed as well?  Or maybe you did in your commit?  Though I'm not quite sure what the aggregate link speed even means any more on devices of any even fairly old vintage, since throughput is hardly the sum of the port speeds. 

I also notice the check are in F5.pm and Port.pm though it is not clear whether those are issues.

Still hunting for my Dlink to Dlink issue, but I feel like with this one I'm getting closer, so at least the SQL statement, once correct, does draw links.
